## Imports

In [28]:
import pandas as pd
import numpy as np
import nfl_data_py as nfl

## Data And Parameters

In [29]:
## modeling input paramters
K = 20  ##max elo change per game
HFA = 50  ##home field advantage
num_simulations = 10000
starting_seed = 1

In [30]:
## game level data
seasons = [2025]
schedule_df = nfl.import_schedules(years=seasons)
schedule_df = schedule_df[schedule_df['game_type']=='REG']
schedule_df=schedule_df[['week','away_team', 'home_team','result']]

In [31]:
## Remove already used weeks
schedule_df = schedule_df[schedule_df['week']!=1]

In [32]:
## elo data
elo = pd.read_csv('elo_2025_week2.csv')  ## elo pulled from https://www.nfeloapp.com/nfl-power-ratings/
teams_df = elo.copy()
teams_df = teams_df[['Team', 'nfelo']]
#make team names consistent
teams_df['Team'] = teams_df['Team'].replace({'LAR': 'LA', 'OAK': 'LV'})

## Function Definitions

In [33]:
def simulate_full_season(teams_df=teams_df.copy(), schedule_df=schedule_df.copy(), K=K, HFA=HFA, seed=starting_seed):
    """
    Input:
        teams_df: elo and team name
        schedule_df: week, home_team, away_team
        K: elo change per game
        HFA: home field advantage
        seed: for randomization

    Output:
        Dataframe: 1 row for each game throughout the entire season
            week. home_team, away_team, home_elo_before, away_elo_before, home_elo_after, away_elo_after, home_win_prob, away_win_prob, simulated_winner

    Methodology:
        Generates a record for each game.  Generates odds of each team winning, and simulates a winner based on those odds
        Updates ELO for both teams after the game, so they can be used in future games, allowing sull season to be simulated at a time
    """
    np.random.seed(seed)
    elo_ratings = teams_df.set_index('Team')['nfelo'].to_dict()
    all_game_results = []

    for week in sorted(schedule_df['week'].unique()):
        week_games = schedule_df[schedule_df['week'] == week]

        for df_index, df_game in week_games.iterrows():
            home_elo = elo_ratings[df_game['home_team']]
            away_elo = elo_ratings[df_game['away_team']]

            home_prob = 1/(1+10 **((away_elo-home_elo+HFA)/400))

            #simulate a winner
            winner = df_game['home_team'] if np.random.rand() < home_prob else df_game['away_team']

            if winner==df_game['home_team']:
                new_home_elo = home_elo + K * (1-home_prob)
                new_away_elo = away_elo + K * (home_prob-1)
            else:
                new_home_elo = home_elo + K * (0-home_prob)
                new_away_elo = away_elo + K * (home_prob-0)
            
            elo_ratings[df_game['home_team']] = new_home_elo
            elo_ratings[df_game['away_team']] = new_away_elo

            all_game_results.append({
                'week': week,
                'home_team': df_game['home_team'],
                'away_team': df_game['away_team'],
                'home_elo_before': home_elo,
                'away_elo_before': away_elo,
                'home_elo_after': new_home_elo,
                'away_elo_after': new_away_elo,
                'home_win_prob': home_prob,
                'away_win_prob': (1-home_prob),
                'simulated_winner': winner})
            
    return pd.DataFrame(all_game_results)

In [34]:
single_season_simulation = simulate_full_season(teams_df,schedule_df, 20, 50, 5)
single_season_simulation.head(5)

,week,home_team,away_team,home_elo_before,away_elo_before,home_elo_after,away_elo_after,home_win_prob,away_win_prob,simulated_winner
0,2,GB,WAS,1594.31,1562.51,1604.833359,1551.986641,0.473832,0.526168,GB
1,2,BAL,CLE,1677.74,1397.72,1661.942734,1413.517266,0.789863,0.210137,CLE
2,2,CIN,JAX,1535.51,1465.71,1544.940726,1456.279274,0.528464,0.471536,CIN
3,2,DAL,NYG,1486.46,1374.47,1474.694479,1386.235521,0.588276,0.411724,NYG
4,2,DET,CHI,1592.11,1479.94,1600.339461,1471.710539,0.588527,0.411473,DET

In [35]:
def global_survivor_path(simulated_season_df, win_metric='home_win_prob'):
    """
    Input:
        simulated_season_df: output of simulate_full_season
        win_metric: what metric you want to use to calculate path
            home_win_prob: maximze win probability, emphasis on home
            home_elo_difference: maximize elo difference between teams, emphasis on home
            home_elo_before: maximize elo before game.  emphasis on home
    
    Output:
        list of teams in order of week selected.  None is first entry for week 0

    Methodology:
        Scans the season looking for the highest value of metric.
        Then that winning team is added to used_teams, and that week is dropped from data
        Then keep iterating through until a team is selected for each week

    """
    survivor_path = [None] * (19)
    used_teams = set()
    remaining_games = simulated_season_df.copy()

    while remaining_games['week'].nunique()>0:
        if win_metric == 'home_win_prob':
            iteration_df = remaining_games.copy()
            iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['home_team']]
            if not iteration_df_1.empty:
                iteration_df_2 = iteration_df_1[iteration_df_1['home_win_prob'] == iteration_df_1['home_win_prob'].max()]
                win_team = iteration_df_2['home_team'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]
            else:
                iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['away_team']]
                iteration_df_2 = iteration_df[iteration_df['away_win_prob'] == iteration_df['away_win_prob'].max()]
                win_team = iteration_df_2['away_win_prob'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]

        
        if win_metric == 'home_elo_difference':
            iteration_df = remaining_games.copy()
            iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['home_team']]
            if not iteration_df_1.empty:
                iteration_df_2 = iteration_df_1[(iteration_df_1['home_elo_before']-iteration_df_1['away_elo_before']) == (iteration_df_1['home_elo_before'] - iteration_df_1['away_elo_before']).max()]
                win_team = iteration_df_2['home_team'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]
            else:
                iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['away_team']]
                iteration_df_2 = iteration_df_1[(iteration_df_1['home_elo_before']-iteration_df_1['away_elo_before']) == (iteration_df_1['home_elo_before'] - iteration_df_1['away_elo_before']).min()]
                win_team = iteration_df_2['away_win_prob'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]
        
        if win_metric == 'home_elo_before':
            iteration_df = remaining_games.copy()
            iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['home_team']]
            if not iteration_df_1.empty:
                iteration_df_2 = iteration_df_1[iteration_df_1['home_elo_before'] == iteration_df_1['home_elo_before'].max()]
                win_team = iteration_df_2['home_team'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]
            else:
                iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['away_team']]
                iteration_df_2 = iteration_df_1[iteration_df_1['away_elo_before'] == iteration_df_1['away_elo_before'].max()]
                win_team = iteration_df_2['away_win_prob'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]

    return survivor_path

In [36]:
single_season_path = global_survivor_path(single_season_simulation, 'home_win_prob')
single_season_path

[None,
 None,
 'ARI',
 'WAS',
 'BUF',
 'IND',
 'LV',
 'DEN',
 'PHI',
 'LA',
 'TB',
 'MIN',
 'DET',
 'LAC',
 'GB',
 'SF',
 'BAL',
 'CIN',
 'ATL']

In [38]:
def simulate_full_season_multiple(teams_df=teams_df.copy(), schedule_df=schedule_df.copy(), K=K, HFA=HFA, simulations=num_simulations, seed = starting_seed, win_metric='home_win_prob'):
    """
    Input:
        teams_df: elo and team name
        schedule_df: week, home_team, away_team
        K: elo change per game
        HFA: home field advantage
        simulations: number of seasons you want to simulate
        seed: for randomization
            win_metric: what metric you want to use to calculate path
            home_win_prob: maximze win probability, emphasis on home
            home_elo_difference: maximize elo difference between teams, emphasis on home
            home_elo_before: maximize elo before game.  emphasis on home

    Output:
        List for each season simualted: contains all game results and best path
            Dictionary 'sim': get the number of the simulation
            Dictionary 'sim_games': get the game data for each simulated game.  Same output as simulate_full_season
            Dictionary 'sim_path': list of the teams selected by week.  Same output as global_survivor_path
    Methodology:
        Runs the simulate_full_season function and then finds the best path for that season global_survivor_path
        Increase the seed by 1, so each simulation is of a different season
    """
    all_season_results = []
    np.random.seed()

    for sim in range(simulations):
        sim_seed = seed+sim
        sim_games = simulate_full_season(teams_df.copy(), schedule_df.copy(), K, HFA, seed=sim_seed)
        sim_path = global_survivor_path(sim_games.copy(), win_metric=win_metric)

        all_season_results.append({
            'sim': sim+1,
            'sim_games': sim_games,
            'sim_path': sim_path})
    return all_season_results

In [39]:
many_season_simulation = simulate_full_season_multiple(teams_df, schedule_df, 20, 50, 100, 1, 'home_win_prob')

In [40]:
## example single season output
many_season_simulation[0]

{'sim': 1,
 'sim_games':      week home_team away_team  home_elo_before  away_elo_before  \
 0       2        GB       WAS      1594.310000      1562.510000
 1       2       BAL       CLE      1677.740000      1397.720000
 2       2       CIN       JAX      1535.510000      1465.710000
 3       2       DAL       NYG      1486.460000      1374.470000
 4       2       DET       CHI      1592.110000      1479.940000
 ..    ...       ...       ...              ...              ...
 251    18       NYG       DAL      1360.556798      1469.920954
 252    18       PHI       WAS      1663.958500      1537.586911
 253    18       PIT       BAL      1460.676024      1714.510134
 254    18        SF       SEA      1504.101360      1543.111541
 255    18        TB       CAR      1435.034960      1341.888840

      home_elo_after  away_elo_after  home_win_prob  away_win_prob  \
 0       1604.833359     1551.986641       0.473832       0.526168
 1       1681.942734     1393.517266       0.789863       0.210137
 2       1544.940726     1456.279274       0.528464       0.471536
 3       1494.694479     1366.235521       0.588276       0.411724
 4       1600.339461     1471.710539       0.588527       0.411473
 ..              ...             ...            ...            ...
 251     1354.846932     1475.630820       0.285493       0.714507
 252     1671.795082     1529.750329       0.608171       0.391829
 253     1457.712581     1717.473577       0.148172       0.851828
 254     1496.608663     1550.604238       0.374635       0.625365
 255     1423.799459     1353.124340       0.561775       0.438225

     simulated_winner
 0                 GB
 1                BAL
 2                CIN
 3                DAL
 4                DET
 ..               ...
 251              DAL
 252              PHI
 253              BAL
 254              SEA
 255              CAR

 [256 rows x 10 columns],
 'sim_path': [None,
  None,
  'BAL',
  'SEA',
  'BUF',
  'ARI',
  'LV',
  'NYJ',
  'PHI',
  'GB',
  'CHI',
  'LA',
  'DET',
  'LAC',
  'TB',
  'SF',
  'DEN',
  'TEN',
  'ATL']}

In [41]:
## example of simulated season number
many_season_simulation[0]['sim']

1

In [42]:
## example of output of each game in simulated season
many_season_simulation[0]['sim_games']

,week,home_team,away_team,home_elo_before,away_elo_before,home_elo_after,away_elo_after,home_win_prob,away_win_prob,simulated_winner
0,2,GB,WAS,1594.310000,1562.510000,1604.833359,1551.986641,0.473832,0.526168,GB
1,2,BAL,CLE,1677.740000,1397.720000,1681.942734,1393.517266,0.789863,0.210137,BAL
2,2,CIN,JAX,1535.510000,1465.710000,1544.940726,1456.279274,0.528464,0.471536,CIN
3,2,DAL,NYG,1486.460000,1374.470000,1494.694479,1366.235521,0.588276,0.411724,DAL
4,2,DET,CHI,1592.110000,1479.940000,1600.339461,1471.710539,0.588527,0.411473,DET
...,...,...,...,...,...,...,...,...,...,...
251,18,NYG,DAL,1360.556798,1469.920954,1354.846932,1475.630820,0.285493,0.714507,DAL
252,18,PHI,WAS,1663.958500,1537.586911,1671.795082,1529.750329,0.608171,0.391829,PHI
253,18,PIT,BAL,1460.676024,1714.510134,1457.712581,1717.473577,0.148172,0.851828,BAL
254,18,SF,SEA,1504.101360,1543.111541,1496.608663,1550.604238,0.374635,0.625365,SEA
255,18,TB,CAR,1435.034960,1341.888840,1423.799459,1353.124340,0.561775,0.438225,CAR

In [43]:
## example of optimal survivor path for simulated season
many_season_simulation[0]['sim_path']

[None,
 None,
 'BAL',
 'SEA',
 'BUF',
 'ARI',
 'LV',
 'NYJ',
 'PHI',
 'GB',
 'CHI',
 'LA',
 'DET',
 'LAC',
 'TB',
 'SF',
 'DEN',
 'TEN',
 'ATL']

In [44]:
def pull_path_from_sim(seasons_list):
    """
    Inputs:
        seasons_list: output of simulate_full_season_multiple

    Outputs: 
        dataframe: simulation number as index, each week is a column
            so 1 row for each simulation with the team selected for that week ina  column

    Methodology:
        Extract the best paths data.
        Then create dataframe of simulations to make for easier analysis
    """
    all_paths = []
    for i in range(len(seasons_list)):
        sim_path = seasons_list[i]['sim_path']
        all_paths.append(sim_path)
    paths_df = pd.DataFrame(all_paths)
    paths_df.index = [f'sim_{i+1}' for i in range(len(all_paths))]
    paths_df.columns = [f'week_{i}' for i in range(paths_df.shape[1])]
    paths_df.drop('week_0', axis=1, inplace=True)

    return paths_df

In [45]:
many_season_simulation_paths = pull_path_from_sim(many_season_simulation)
many_season_simulation_paths

,week_1,week_2,week_3,week_4,week_5,week_6,week_7,week_8,week_9,week_10,week_11,week_12,week_13,week_14,week_15,week_16,week_17,week_18
sim_1,None,BAL,SEA,BUF,ARI,LV,NYJ,PHI,GB,CHI,LA,DET,LAC,TB,SF,DEN,TEN,ATL
sim_2,None,ARI,SEA,BUF,LA,PIT,CHI,NE,GB,NYJ,ATL,BAL,MIA,DET,PHI,HOU,WAS,TB
sim_3,None,ARI,SEA,BUF,NO,PIT,DEN,PHI,LA,CHI,ATL,LV,LAC,TB,SF,BAL,KC,CIN
sim_4,None,BAL,SEA,BUF,NO,PIT,KC,PHI,GB,NYJ,ARI,CIN,MIA,TB,SF,WAS,LAC,ATL
sim_5,None,ARI,WAS,BUF,IND,LV,DEN,PHI,LA,TB,MIN,DET,LAC,GB,SF,BAL,CIN,ATL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
sim_96,None,ARI,WAS,BUF,IND,GB,NYJ,PHI,LA,CHI,ATL,DET,MIA,CLE,SF,BAL,LV,TB
sim_97,None,ARI,SEA,BUF,LAC,WAS,DEN,IND,GB,TB,MIN,DET,PHI,KC,JAX,BAL,LV,LA
sim_98,None,BAL,WAS,HOU,ARI,PIT,DEN,PHI,GB,CHI,ATL,DET,MIA,TB,SF,IND,KC,BUF
sim_99,None,DAL,SEA,BUF,ARI,LV,CHI,IND,GB,DEN,ATL,CIN,MIA,TB,PHI,BAL,TEN,JAX
sim_100,None,BAL,SEA,HOU,BUF,PIT,KC,PHI,LA,CHI,ARI,DET,WAS,TB,SF,DEN,LV,ATL

## Running Simulations And Analysis

In [46]:
## week 1 picks over simulations
simulated_data_home_elo_before = simulate_full_season_multiple(teams_df.copy(), schedule_df.copy(), K, HFA, simulations=10000, seed = starting_seed, win_metric='home_elo_before')
simulated_paths_home_elo_before = pull_path_from_sim(simulated_data_home_elo_before)
simulated_paths_home_elo_before.value_counts('week_2')

week_2
BAL    1623
DET    1484
CIN    1172
MIN     958
ARI     944
GB      890
DAL     641
KC      565
PIT     468
HOU     443
MIA     211
IND     186
LV      134
TEN      57
NO       49
NYJ      40
LA       24
TB       23
SEA      20
LAC      18
DEN      15
ATL      14
WAS      13
SF        5
JAX       1
PHI       1
BUF       1
Name: count, dtype: int64

In [47]:
## exmaple simulation
simulated_single_path_home_elo_before = simulated_paths_home_elo_before.iloc[[0]]
simulated_single_path_home_elo_before

,week_1,week_2,week_3,week_4,week_5,week_6,week_7,week_8,week_9,week_10,week_11,week_12,week_13,week_14,week_15,week_16,week_17,week_18
sim_1,None,DET,CHI,LV,BUF,ATL,CIN,LAC,GB,SEA,CLE,ARI,PHI,BAL,KC,DEN,WAS,LA

In [52]:
## week 1 picks over simulations
simulated_data_home_win_prob = simulate_full_season_multiple(teams_df.copy(), schedule_df.copy(), K, HFA, simulations=10000, seed = 1, win_metric='home_win_prob')
simulated_paths_home_win_prob = pull_path_from_sim(simulated_data_home_win_prob)
simulated_paths_home_win_prob.value_counts('week_2')

week_2
BAL    4672
ARI    3129
DAL    1012
DET     412
CIN     212
MIN     198
MIA      94
HOU      41
PIT      39
IND      35
GB       28
KC       27
LA       21
SF       21
NO       19
TEN      14
NYJ       7
LV        7
LAC       5
TB        2
NYG       1
NE        1
SEA       1
DEN       1
WAS       1
Name: count, dtype: int64

In [53]:
## exmaple simulation
simulated_sinlge_path_home_win_prob = simulated_paths_home_win_prob.iloc[[0]]
simulated_sinlge_path_home_win_prob

,week_1,week_2,week_3,week_4,week_5,week_6,week_7,week_8,week_9,week_10,week_11,week_12,week_13,week_14,week_15,week_16,week_17,week_18
sim_1,None,BAL,SEA,BUF,ARI,LV,NYJ,PHI,GB,CHI,LA,DET,LAC,TB,SF,DEN,TEN,ATL

In [50]:
## week 1 picks over simulations
simulated_data_home_elo_difference = simulate_full_season_multiple(teams_df.copy(), schedule_df.copy(), K, HFA, simulations=10000, seed = 1, win_metric='home_elo_difference')
simulated_paths_home_elo_difference = pull_path_from_sim(simulated_data_home_elo_difference)
simulated_paths_home_elo_difference.value_counts('week_2')

Series([], Name: count, dtype: int64)

In [51]:
## exmaple simulation
simulated_sinlge_path_home_elo_difference = simulated_paths_home_elo_difference.iloc[[0]]
simulated_sinlge_path_home_elo_difference

,week_1,week_2,week_3,week_4,week_5,week_6,week_7,week_8,week_9,week_10,week_11,week_12,week_13,week_14,week_15,week_16,week_17,week_18
sim_1,None,BAL,SEA,BUF,ARI,LV,NYJ,PHI,GB,CHI,LA,DET,LAC,TB,SF,DEN,TEN,ATL