## Imports

In [1]:
import pandas as pd
import numpy as np
import nfl_data_py as nfl

## Data And Parameters

In [2]:
## modeling input paramters
K = 20  ##max elo change per game
HFA = 50  ##home field advantage
num_simulations = 10000
starting_seed = 1

In [3]:
## game level data
seasons = [2025]
schedule_df = nfl.import_schedules(years=seasons)
schedule_df = schedule_df[schedule_df['game_type']=='REG']
schedule_df=schedule_df[['week','away_team', 'home_team','result']]

In [4]:
## Remove already used weeks
schedule_df = schedule_df[schedule_df['week']!=1]
schedule_df = schedule_df[schedule_df['week']!=2]
schedule_df = schedule_df[schedule_df['week']!=3]
schedule_df = schedule_df[schedule_df['week']!=4]
schedule_df = schedule_df[schedule_df['week']!=5]

In [5]:
## elo data
elo = pd.read_csv('elo_2025_week6.csv')  ## elo pulled from https://www.nfeloapp.com/nfl-power-ratings/
teams_df = elo.copy()
teams_df = teams_df[['Team', 'nfelo']]
#make team names consistent
teams_df['Team'] = teams_df['Team'].replace({'LAR': 'LA', 'OAK': 'LV'})

## Function Definitions

In [6]:
def simulate_full_season(teams_df=teams_df.copy(), schedule_df=schedule_df.copy(), K=K, HFA=HFA, seed=starting_seed):
    """
    Input:
        teams_df: elo and team name
        schedule_df: week, home_team, away_team
        K: elo change per game
        HFA: home field advantage
        seed: for randomization

    Output:
        Dataframe: 1 row for each game throughout the entire season
            week. home_team, away_team, home_elo_before, away_elo_before, home_elo_after, away_elo_after, home_win_prob, away_win_prob, simulated_winner

    Methodology:
        Generates a record for each game.  Generates odds of each team winning, and simulates a winner based on those odds
        Updates ELO for both teams after the game, so they can be used in future games, allowing sull season to be simulated at a time
    """
    np.random.seed(seed)
    elo_ratings = teams_df.set_index('Team')['nfelo'].to_dict()
    all_game_results = []

    for week in sorted(schedule_df['week'].unique()):
        week_games = schedule_df[schedule_df['week'] == week]

        for df_index, df_game in week_games.iterrows():
            home_elo = elo_ratings[df_game['home_team']]
            away_elo = elo_ratings[df_game['away_team']]

            home_prob = 1/(1+10 **((away_elo-home_elo+HFA)/400))

            #simulate a winner
            winner = df_game['home_team'] if np.random.rand() < home_prob else df_game['away_team']

            if winner==df_game['home_team']:
                new_home_elo = home_elo + K * (1-home_prob)
                new_away_elo = away_elo + K * (home_prob-1)
            else:
                new_home_elo = home_elo + K * (0-home_prob)
                new_away_elo = away_elo + K * (home_prob-0)
            
            elo_ratings[df_game['home_team']] = new_home_elo
            elo_ratings[df_game['away_team']] = new_away_elo

            all_game_results.append({
                'week': week,
                'home_team': df_game['home_team'],
                'away_team': df_game['away_team'],
                'home_elo_before': home_elo,
                'away_elo_before': away_elo,
                'home_elo_after': new_home_elo,
                'away_elo_after': new_away_elo,
                'home_win_prob': home_prob,
                'away_win_prob': (1-home_prob),
                'simulated_winner': winner})
            
    return pd.DataFrame(all_game_results)

In [7]:
single_season_simulation = simulate_full_season(teams_df,schedule_df, 20, 50, 5)
single_season_simulation.head(5)

,week,home_team,away_team,home_elo_before,away_elo_before,home_elo_after,away_elo_after,home_win_prob,away_win_prob,simulated_winner
0,5,LA,SF,1576.40,1528.70,1586.466198,1518.633802,0.496690,0.503310,LA
1,5,CLE,MIN,1329.86,1522.43,1325.892066,1526.397934,0.198397,0.801603,MIN
2,5,BAL,HOU,1529.01,1498.79,1539.578700,1488.221300,0.471565,0.528435,BAL
3,5,CAR,MIA,1358.22,1450.59,1352.102806,1456.707194,0.305860,0.694140,MIA
4,5,IND,LV,1511.77,1418.20,1520.522487,1409.447513,0.562376,0.437624,IND

In [7]:
def global_survivor_path(simulated_season_df, win_metric='home_win_prob'):
    """
    Input:
        simulated_season_df: output of simulate_full_season
        win_metric: what metric you want to use to calculate path
            home_win_prob: maximze win probability, emphasis on home
            home_elo_difference: maximize elo difference between teams, emphasis on home
            home_elo_before: maximize elo before game.  emphasis on home
    
    Output:
        list of teams in order of week selected.  None is first entry for week 0

    Methodology:
        Scans the season looking for the highest value of metric.
        Then that winning team is added to used_teams, and that week is dropped from data
        Then keep iterating through until a team is selected for each week

    """
    survivor_path = [None] * (19)
    used_teams = set()
    used_teams.update(['WAS', 'BAL', 'SEA', 'BUF', 'ARI'])
    remaining_games = simulated_season_df.copy()

    while remaining_games['week'].nunique()>0:
        if win_metric == 'home_win_prob':
            iteration_df = remaining_games.copy()
            iteration_df = iteration_df[~iteration_df['simulated_winner'].isin(used_teams)]
            iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['home_team']]
            if not iteration_df_1.empty:
                iteration_df_2 = iteration_df_1[iteration_df_1['home_win_prob'] == iteration_df_1['home_win_prob'].max()]
                win_team = iteration_df_2['home_team'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]
            else:
                iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['away_team']]
                iteration_df_2 = iteration_df[iteration_df['away_win_prob'] == iteration_df['away_win_prob'].max()]
                win_team = iteration_df_2['away_win_prob'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]

        
        if win_metric == 'home_elo_difference':
            iteration_df = remaining_games.copy()
            iteration_df = iteration_df[~iteration_df['simulated_winner'].isin(used_teams)]
            iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['home_team']]
            if not iteration_df_1.empty:
                iteration_df_2 = iteration_df_1[(iteration_df_1['home_elo_before']-iteration_df_1['away_elo_before']) == (iteration_df_1['home_elo_before'] - iteration_df_1['away_elo_before']).max()]
                win_team = iteration_df_2['home_team'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]
            else:
                iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['away_team']]
                iteration_df_2 = iteration_df_1[(iteration_df_1['home_elo_before']-iteration_df_1['away_elo_before']) == (iteration_df_1['home_elo_before'] - iteration_df_1['away_elo_before']).min()]
                win_team = iteration_df_2['away_win_prob'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]
        
        if win_metric == 'home_elo_before':
            iteration_df = remaining_games.copy()
            iteration_df = iteration_df[~iteration_df['simulated_winner'].isin(used_teams)]
            iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['home_team']]
            if not iteration_df_1.empty:
                iteration_df_2 = iteration_df_1[iteration_df_1['home_elo_before'] == iteration_df_1['home_elo_before'].max()]
                win_team = iteration_df_2['home_team'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]
            else:
                iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['away_team']]
                iteration_df_2 = iteration_df_1[iteration_df_1['away_elo_before'] == iteration_df_1['away_elo_before'].max()]
                win_team = iteration_df_2['away_win_prob'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]

    return survivor_path

In [8]:
single_season_path = global_survivor_path(single_season_simulation, 'home_win_prob')
single_season_path

NameError: name 'single_season_simulation' is not defined

In [9]:
def simulate_full_season_multiple(teams_df=teams_df.copy(), schedule_df=schedule_df.copy(), K=K, HFA=HFA, simulations=num_simulations, seed = starting_seed, win_metric='home_win_prob'):
    """
    Input:
        teams_df: elo and team name
        schedule_df: week, home_team, away_team
        K: elo change per game
        HFA: home field advantage
        simulations: number of seasons you want to simulate
        seed: for randomization
            win_metric: what metric you want to use to calculate path
            home_win_prob: maximze win probability, emphasis on home
            home_elo_difference: maximize elo difference between teams, emphasis on home
            home_elo_before: maximize elo before game.  emphasis on home

    Output:
        List for each season simualted: contains all game results and best path
            Dictionary 'sim': get the number of the simulation
            Dictionary 'sim_games': get the game data for each simulated game.  Same output as simulate_full_season
            Dictionary 'sim_path': list of the teams selected by week.  Same output as global_survivor_path
    Methodology:
        Runs the simulate_full_season function and then finds the best path for that season global_survivor_path
        Increase the seed by 1, so each simulation is of a different season
    """
    all_season_results = []
    np.random.seed()

    for sim in range(simulations):
        sim_seed = seed+sim
        sim_games = simulate_full_season(teams_df.copy(), schedule_df.copy(), K, HFA, seed=sim_seed)
        sim_path = global_survivor_path(sim_games.copy(), win_metric=win_metric)

        all_season_results.append({
            'sim': sim+1,
            'sim_games': sim_games,
            'sim_path': sim_path})
    return all_season_results

In [10]:
many_season_simulation = simulate_full_season_multiple(teams_df, schedule_df, 20, 50, 100, 1, 'home_win_prob')

In [11]:
## example single season output
many_season_simulation[0]

{'sim': 1,
 'sim_games':      week home_team away_team  home_elo_before  away_elo_before  \
 0       6       NYG       PHI      1327.370000      1616.170000
 1       6       NYJ       DEN      1431.580000      1574.340000
 2       6       BAL        LA      1454.030000      1576.700000
 3       6       CAR       DAL      1367.140000      1503.720000
 4       6       IND       ARI      1527.770000      1455.220000
 ..    ...       ...       ...              ...              ...
 189    18       NYG       DAL      1353.111840      1537.249987
 190    18       PHI       WAS      1646.894694      1521.233732
 191    18       PIT       BAL      1552.569122      1450.463586
 192    18        SF       SEA      1491.791220      1539.787536
 193    18        TB       CAR      1440.406094      1411.241796

      home_elo_after  away_elo_after  home_win_prob  away_win_prob  \
 0       1324.879564     1618.660436       0.124522       0.875478
 1       1426.621149     1579.298851       0.247943       0.752057
 2       1468.627421     1562.102579       0.270129       0.729871
 3       1362.047292     1508.812708       0.254635       0.745365
 4       1537.121869     1445.868131       0.532407       0.467593
 ..              ...             ...            ...            ...
 189     1348.987259     1541.374568       0.206229       0.793771
 190     1654.750780     1513.377646       0.607196       0.392804
 191     1561.080548     1441.952161       0.574429       0.425571
 192     1484.539289     1547.039467       0.362597       0.637403
 193     1431.005076     1420.642814       0.470051       0.529949

     simulated_winner
 0                PHI
 1                DEN
 2                BAL
 3                DAL
 4                IND
 ..               ...
 189              DAL
 190              PHI
 191              PIT
 192              SEA
 193              CAR

 [194 rows x 10 columns],
 'sim_path': [None,
  None,
  None,
  None,
  None,
  None,
  'GB',
  'DEN',
  'ATL',
  'LA',
  'CHI',
  'NE',
  'DET',
  'PHI',
  'NYJ',
  'KC',
  'MIA',
  'LAC',
  'JAX']}

In [12]:
## example of simulated season number
many_season_simulation[0]['sim']

1

In [13]:
## example of output of each game in simulated season
many_season_simulation[0]['sim_games']

,week,home_team,away_team,home_elo_before,away_elo_before,home_elo_after,away_elo_after,home_win_prob,away_win_prob,simulated_winner
0,6,NYG,PHI,1327.370000,1616.170000,1324.879564,1618.660436,0.124522,0.875478,PHI
1,6,NYJ,DEN,1431.580000,1574.340000,1426.621149,1579.298851,0.247943,0.752057,DEN
2,6,BAL,LA,1454.030000,1576.700000,1468.627421,1562.102579,0.270129,0.729871,BAL
3,6,CAR,DAL,1367.140000,1503.720000,1362.047292,1508.812708,0.254635,0.745365,DAL
4,6,IND,ARI,1527.770000,1455.220000,1537.121869,1445.868131,0.532407,0.467593,IND
...,...,...,...,...,...,...,...,...,...,...
189,18,NYG,DAL,1353.111840,1537.249987,1348.987259,1541.374568,0.206229,0.793771,DAL
190,18,PHI,WAS,1646.894694,1521.233732,1654.750780,1513.377646,0.607196,0.392804,PHI
191,18,PIT,BAL,1552.569122,1450.463586,1561.080548,1441.952161,0.574429,0.425571,PIT
192,18,SF,SEA,1491.791220,1539.787536,1484.539289,1547.039467,0.362597,0.637403,SEA
193,18,TB,CAR,1440.406094,1411.241796,1431.005076,1420.642814,0.470051,0.529949,CAR

In [14]:
## example of optimal survivor path for simulated season
many_season_simulation[0]['sim_path']

[None,
 None,
 None,
 None,
 None,
 None,
 'GB',
 'DEN',
 'ATL',
 'LA',
 'CHI',
 'NE',
 'DET',
 'PHI',
 'NYJ',
 'KC',
 'MIA',
 'LAC',
 'JAX']

In [15]:
def pull_path_from_sim(seasons_list):
    """
    Inputs:
        seasons_list: output of simulate_full_season_multiple

    Outputs: 
        dataframe: simulation number as index, each week is a column
            so 1 row for each simulation with the team selected for that week ina  column

    Methodology:
        Extract the best paths data.
        Then create dataframe of simulations to make for easier analysis
    """
    all_paths = []
    for i in range(len(seasons_list)):
        sim_path = seasons_list[i]['sim_path']
        all_paths.append(sim_path)
    paths_df = pd.DataFrame(all_paths)
    paths_df.index = [f'sim_{i+1}' for i in range(len(all_paths))]
    paths_df.columns = [f'week_{i}' for i in range(paths_df.shape[1])]
    paths_df.drop('week_0', axis=1, inplace=True)

    return paths_df

In [16]:
many_season_simulation_paths = pull_path_from_sim(many_season_simulation)
many_season_simulation_paths

,week_1,week_2,week_3,week_4,week_5,week_6,week_7,week_8,week_9,week_10,week_11,week_12,week_13,week_14,week_15,week_16,week_17,week_18
sim_1,None,None,None,None,None,GB,DEN,ATL,LA,CHI,NE,DET,PHI,NYJ,KC,MIA,LAC,JAX
sim_2,None,None,None,None,None,PIT,DEN,PHI,GB,NYJ,ATL,DET,LAC,KC,SF,HOU,IND,TB
sim_3,None,None,None,None,None,PIT,DEN,PHI,GB,CHI,ATL,DET,MIA,TB,SF,HOU,LV,JAX
sim_4,None,None,None,None,None,PIT,CHI,PHI,LA,DEN,MIN,DET,IND,KC,HOU,MIA,GB,ATL
sim_5,None,None,None,None,None,GB,DEN,PHI,LA,JAX,ATL,SF,LAC,KC,CHI,DET,MIA,TB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
sim_96,None,None,None,None,None,GB,DEN,PHI,LA,CHI,PIT,DET,MIA,KC,SF,DAL,TEN,JAX
sim_97,None,None,None,None,None,GB,DEN,PHI,LA,CHI,PIT,DET,NE,TB,NO,HOU,NYJ,JAX
sim_98,None,None,None,None,None,PIT,DEN,PHI,GB,CHI,ATL,DET,NE,KC,DAL,HOU,LV,TB
sim_99,None,None,None,None,None,MIA,MIN,PHI,LA,CHI,PIT,DET,LAC,CLE,SF,DEN,LV,ATL
sim_100,None,None,None,None,None,PIT,DEN,PHI,LA,CHI,MIA,DET,NE,TB,SF,HOU,GB,JAX

## Running Simulations And Analysis

In [17]:
## week 1 picks over simulations
simulated_data_home_elo_before = simulate_full_season_multiple(teams_df.copy(), schedule_df.copy(), K, HFA, simulations=10000, seed = starting_seed, win_metric='home_elo_before')
simulated_paths_home_elo_before = pull_path_from_sim(simulated_data_home_elo_before)
simulated_paths_home_elo_before.value_counts('week_6')

week_6
GB     2322
TB     1422
IND    1396
PIT    1364
JAX    1005
LV      478
MIA     451
KC      439
ATL     336
NYJ     277
CAR     117
NO      113
LAC      71
DAL      64
NYG      32
LA       30
NE       28
SF       20
CHI      14
PHI       8
DEN       8
CIN       2
CLE       1
DET       1
TEN       1
Name: count, dtype: int64

In [18]:
## exmaple simulation
simulated_single_path_home_elo_before = simulated_paths_home_elo_before.iloc[[0]]
simulated_single_path_home_elo_before

,week_1,week_2,week_3,week_4,week_5,week_6,week_7,week_8,week_9,week_10,week_11,week_12,week_13,week_14,week_15,week_16,week_17,week_18
sim_1,None,None,None,None,None,GB,DEN,LAC,NE,HOU,JAX,LA,DET,MIN,PIT,MIA,KC,PHI

In [19]:
## week 1 picks over simulations
simulated_data_home_win_prob = simulate_full_season_multiple(teams_df.copy(), schedule_df.copy(), K, HFA, simulations=10000, seed = 1, win_metric='home_win_prob')
simulated_paths_home_win_prob = pull_path_from_sim(simulated_data_home_win_prob)
simulated_paths_home_win_prob.value_counts('week_6')

week_6
PIT    5197
GB     2085
LV     1036
IND     650
NO      157
MIA     154
JAX     138
DAL     130
KC      122
TB      105
CAR      72
NYJ      60
ATL      26
NYG      22
PHI      16
DEN      11
LA        8
NE        5
LAC       3
TEN       3
Name: count, dtype: int64

In [20]:
## exmaple simulation
simulated_sinlge_path_home_win_prob = simulated_paths_home_win_prob.iloc[[0]]
simulated_sinlge_path_home_win_prob

,week_1,week_2,week_3,week_4,week_5,week_6,week_7,week_8,week_9,week_10,week_11,week_12,week_13,week_14,week_15,week_16,week_17,week_18
sim_1,None,None,None,None,None,GB,DEN,ATL,LA,CHI,NE,DET,PHI,NYJ,KC,MIA,LAC,JAX

In [21]:
## week 1 picks over simulations
simulated_data_home_elo_difference = simulate_full_season_multiple(teams_df.copy(), schedule_df.copy(), K, HFA, simulations=10000, seed = 1, win_metric='home_elo_difference')
simulated_paths_home_elo_difference = pull_path_from_sim(simulated_data_home_elo_difference)
simulated_paths_home_elo_difference.value_counts('week_6')

week_6
PIT    5197
GB     2085
LV     1036
IND     650
NO      157
MIA     154
JAX     138
DAL     130
KC      122
TB      105
CAR      72
NYJ      60
ATL      26
NYG      22
PHI      16
DEN      11
LA        8
NE        5
LAC       3
TEN       3
Name: count, dtype: int64

In [22]:
## exmaple simulation
simulated_sinlge_path_home_elo_difference = simulated_paths_home_elo_difference.iloc[[0]]
simulated_sinlge_path_home_elo_difference

,week_1,week_2,week_3,week_4,week_5,week_6,week_7,week_8,week_9,week_10,week_11,week_12,week_13,week_14,week_15,week_16,week_17,week_18
sim_1,None,None,None,None,None,GB,DEN,ATL,LA,CHI,NE,DET,PHI,NYJ,KC,MIA,LAC,JAX

In [27]:
simulated_paths_home_elo_difference.value_counts('week_6')

week_6
PIT    5197
GB     2085
LV     1036
IND     650
NO      157
MIA     154
JAX     138
DAL     130
KC      122
TB      105
CAR      72
NYJ      60
ATL      26
NYG      22
PHI      16
DEN      11
LA        8
NE        5
LAC       3
TEN       3
Name: count, dtype: int64

In [31]:
simulated_paths_home_elo_before.value_counts('week_8')

week_8
PHI    2717
IND    1611
KC     1196
DEN    1101
LAC     765
ATL     638
HOU     577
NE      503
PIT     415
CIN     176
NO       54
MIN      49
CAR      43
TB       37
DAL      35
SF       30
CHI      27
MIA      12
NYJ      11
GB        3
Name: count, dtype: int64

In [32]:
simulated_paths_home_win_prob.value_counts('week_8')

week_8
PHI    7804
IND    1530
NE      295
CIN      68
KC       66
ATL      60
HOU      47
LAC      38
NYJ      18
NO       18
CAR      15
DEN       8
TB        8
PIT       7
CHI       5
MIN       5
SF        5
CLE       2
GB        1
Name: count, dtype: int64

In [33]:
simulated_paths_home_elo_difference.value_counts('week_8')

week_8
PHI    7804
IND    1530
NE      295
CIN      68
KC       66
ATL      60
HOU      47
LAC      38
NYJ      18
NO       18
CAR      15
DEN       8
TB        8
PIT       7
CHI       5
MIN       5
SF        5
CLE       2
GB        1
Name: count, dtype: int64