## Imports

In [4]:
import pandas as pd
import numpy as np
import nfl_data_py as nfl

## Data And Parameters

In [5]:
## modeling input paramters
K = 20  ##max elo change per game
HFA = 50  ##home field advantage
num_simulations = 10000
starting_seed = 1

In [6]:
## game level data
seasons = [2025]
schedule_df = nfl.import_schedules(years=seasons)
schedule_df = schedule_df[schedule_df['game_type']=='REG']
schedule_df=schedule_df[['week','away_team', 'home_team','result']]

In [7]:
## Remove already used weeks
schedule_df = schedule_df[schedule_df['week']!=1]
schedule_df = schedule_df[schedule_df['week']!=2]
schedule_df = schedule_df[schedule_df['week']!=3]
schedule_df = schedule_df[schedule_df['week']!=4]
schedule_df = schedule_df[schedule_df['week']!=5]
schedule_df = schedule_df[schedule_df['week']!=6]
schedule_df = schedule_df[schedule_df['week']!=7]
schedule_df = schedule_df[schedule_df['week']!=8]
schedule_df = schedule_df[schedule_df['week']!=9]
schedule_df = schedule_df[schedule_df['week']!=10]
schedule_df = schedule_df[schedule_df['week']!=11]
schedule_df = schedule_df[schedule_df['week']!=12]
schedule_df = schedule_df[schedule_df['week']!=13]
schedule_df = schedule_df[schedule_df['week']!=14]

In [8]:
## elo data
elo = pd.read_csv('elo_2025_week15.csv')  ## elo pulled from https://www.nfeloapp.com/nfl-power-ratings/
teams_df = elo.copy()
teams_df = teams_df[['Team', 'nfelo']]
#make team names consistent
teams_df['Team'] = teams_df['Team'].replace({'LAR': 'LA', 'OAK': 'LV'})

## Function Definitions

In [9]:
def simulate_full_season(teams_df=teams_df.copy(), schedule_df=schedule_df.copy(), K=K, HFA=HFA, seed=starting_seed):
    """
    Input:
        teams_df: elo and team name
        schedule_df: week, home_team, away_team
        K: elo change per game
        HFA: home field advantage
        seed: for randomization

    Output:
        Dataframe: 1 row for each game throughout the entire season
            week. home_team, away_team, home_elo_before, away_elo_before, home_elo_after, away_elo_after, home_win_prob, away_win_prob, simulated_winner

    Methodology:
        Generates a record for each game.  Generates odds of each team winning, and simulates a winner based on those odds
        Updates ELO for both teams after the game, so they can be used in future games, allowing sull season to be simulated at a time
    """
    np.random.seed(seed)
    elo_ratings = teams_df.set_index('Team')['nfelo'].to_dict()
    all_game_results = []

    for week in sorted(schedule_df['week'].unique()):
        week_games = schedule_df[schedule_df['week'] == week]

        for df_index, df_game in week_games.iterrows():
            home_elo = elo_ratings[df_game['home_team']]
            away_elo = elo_ratings[df_game['away_team']]

            home_prob = 1/(1+10 **((away_elo-home_elo+HFA)/400))

            #simulate a winner
            winner = df_game['home_team'] if np.random.rand() < home_prob else df_game['away_team']

            if winner==df_game['home_team']:
                new_home_elo = home_elo + K * (1-home_prob)
                new_away_elo = away_elo + K * (home_prob-1)
            else:
                new_home_elo = home_elo + K * (0-home_prob)
                new_away_elo = away_elo + K * (home_prob-0)
            
            elo_ratings[df_game['home_team']] = new_home_elo
            elo_ratings[df_game['away_team']] = new_away_elo

            all_game_results.append({
                'week': week,
                'home_team': df_game['home_team'],
                'away_team': df_game['away_team'],
                'home_elo_before': home_elo,
                'away_elo_before': away_elo,
                'home_elo_after': new_home_elo,
                'away_elo_after': new_away_elo,
                'home_win_prob': home_prob,
                'away_win_prob': (1-home_prob),
                'simulated_winner': winner})
            
    return pd.DataFrame(all_game_results)

In [10]:
single_season_simulation = simulate_full_season(teams_df,schedule_df, 20, 50, 5)
single_season_simulation.head(5)

,week,home_team,away_team,home_elo_before,away_elo_before,home_elo_after,away_elo_after,home_win_prob,away_win_prob,simulated_winner
0,15,TB,ATL,1458.33,1427.81,1468.890093,1417.249907,0.471995,0.528005,TB
1,15,CHI,CLE,1499.42,1368.95,1487.144432,1381.225568,0.613778,0.386222,CLE
2,15,CIN,BAL,1474.08,1550.97,1487.578026,1537.471974,0.325099,0.674901,CIN
3,15,HOU,ARI,1561.41,1391.82,1548.097713,1405.132287,0.665614,0.334386,ARI
4,15,JAX,NYJ,1513.62,1312.80,1519.532623,1306.887377,0.704369,0.295631,JAX

In [11]:
def global_survivor_path(simulated_season_df, win_metric='home_win_prob'):
    """
    Input:
        simulated_season_df: output of simulate_full_season
        win_metric: what metric you want to use to calculate path
            home_win_prob: maximze win probability, emphasis on home
            home_elo_difference: maximize elo difference between teams, emphasis on home
            home_elo_before: maximize elo before game.  emphasis on home
    
    Output:
        list of teams in order of week selected.  None is first entry for week 0

    Methodology:
        Scans the season looking for the highest value of metric.
        Then that winning team is added to used_teams, and that week is dropped from data
        Then keep iterating through until a team is selected for each week

    """
    survivor_path = [None] * (19)
    used_teams = set()
    used_teams.update(['WAS', 'BAL', 'SEA', 'BUF', 'ARI', 'GB', 'KC', 'IND', 'LAR', 'DET', 'LA', 'DEN', 'NE', 'PIT'])
    remaining_games = simulated_season_df.copy()

    while remaining_games['week'].nunique()>0:
        if win_metric == 'home_win_prob':
            iteration_df = remaining_games.copy()
            iteration_df = iteration_df[~iteration_df['simulated_winner'].isin(used_teams)]
            iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['home_team']]
            if not iteration_df_1.empty:
                iteration_df_2 = iteration_df_1[iteration_df_1['home_win_prob'] == iteration_df_1['home_win_prob'].max()]
                win_team = iteration_df_2['home_team'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]
            else:
                iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['away_team']]
                iteration_df_2 = iteration_df[iteration_df['away_win_prob'] == iteration_df['away_win_prob'].max()]
                win_team = iteration_df_2['away_win_prob'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]

        
        if win_metric == 'home_elo_difference':
            iteration_df = remaining_games.copy()
            iteration_df = iteration_df[~iteration_df['simulated_winner'].isin(used_teams)]
            iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['home_team']]
            if not iteration_df_1.empty:
                iteration_df_2 = iteration_df_1[(iteration_df_1['home_elo_before']-iteration_df_1['away_elo_before']) == (iteration_df_1['home_elo_before'] - iteration_df_1['away_elo_before']).max()]
                win_team = iteration_df_2['home_team'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]
            else:
                iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['away_team']]
                iteration_df_2 = iteration_df_1[(iteration_df_1['home_elo_before']-iteration_df_1['away_elo_before']) == (iteration_df_1['home_elo_before'] - iteration_df_1['away_elo_before']).min()]
                win_team = iteration_df_2['away_win_prob'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]
        
        if win_metric == 'home_elo_before':
            iteration_df = remaining_games.copy()
            iteration_df = iteration_df[~iteration_df['simulated_winner'].isin(used_teams)]
            iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['home_team']]
            if not iteration_df_1.empty:
                iteration_df_2 = iteration_df_1[iteration_df_1['home_elo_before'] == iteration_df_1['home_elo_before'].max()]
                win_team = iteration_df_2['home_team'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]
            else:
                iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['away_team']]
                iteration_df_2 = iteration_df_1[iteration_df_1['away_elo_before'] == iteration_df_1['away_elo_before'].max()]
                win_team = iteration_df_2['away_win_prob'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]

    return survivor_path

In [12]:
single_season_path = global_survivor_path(single_season_simulation, 'home_win_prob')
single_season_path

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'PHI',
 'HOU',
 'LV',
 'JAX']

In [13]:
def simulate_full_season_multiple(teams_df=teams_df.copy(), schedule_df=schedule_df.copy(), K=K, HFA=HFA, simulations=num_simulations, seed = starting_seed, win_metric='home_win_prob'):
    """
    Input:
        teams_df: elo and team name
        schedule_df: week, home_team, away_team
        K: elo change per game
        HFA: home field advantage
        simulations: number of seasons you want to simulate
        seed: for randomization
            win_metric: what metric you want to use to calculate path
            home_win_prob: maximze win probability, emphasis on home
            home_elo_difference: maximize elo difference between teams, emphasis on home
            home_elo_before: maximize elo before game.  emphasis on home

    Output:
        List for each season simualted: contains all game results and best path
            Dictionary 'sim': get the number of the simulation
            Dictionary 'sim_games': get the game data for each simulated game.  Same output as simulate_full_season
            Dictionary 'sim_path': list of the teams selected by week.  Same output as global_survivor_path
    Methodology:
        Runs the simulate_full_season function and then finds the best path for that season global_survivor_path
        Increase the seed by 1, so each simulation is of a different season
    """
    all_season_results = []
    np.random.seed()

    for sim in range(simulations):
        sim_seed = seed+sim
        sim_games = simulate_full_season(teams_df.copy(), schedule_df.copy(), K, HFA, seed=sim_seed)
        sim_path = global_survivor_path(sim_games.copy(), win_metric=win_metric)

        all_season_results.append({
            'sim': sim+1,
            'sim_games': sim_games,
            'sim_path': sim_path})
    return all_season_results

In [14]:
many_season_simulation = simulate_full_season_multiple(teams_df, schedule_df, 20, 50, 100, 1, 'home_win_prob')

In [15]:
## example single season output
many_season_simulation[0]

{'sim': 1,
 'sim_games':     week home_team away_team  home_elo_before  away_elo_before  \
 0     15        TB       ATL      1458.330000      1427.810000
 1     15       CHI       CLE      1499.420000      1368.950000
 2     15       CIN       BAL      1474.080000      1550.970000
 3     15       HOU       ARI      1561.410000      1391.820000
 4     15       JAX       NYJ      1513.620000      1312.800000
 ..   ...       ...       ...              ...              ...
 59    18       NYG       DAL      1391.441613      1517.104381
 60    18       PHI       WAS      1611.875542      1369.350126
 61    18       PIT       BAL      1490.526244      1560.810938
 62    18        SF       SEA      1548.174808      1684.209543
 63    18        TB       CAR      1464.634135      1424.261893

     home_elo_after  away_elo_after  home_win_prob  away_win_prob  \
 0      1468.890093     1417.249907       0.471995       0.528005
 1      1487.144432     1381.225568       0.613778       0.386222
 2      1487.578026     1537.471974       0.325099       0.674901
 3      1568.097713     1385.132287       0.665614       0.334386
 4      1519.532623     1306.887377       0.704369       0.295631
 ..             ...             ...            ...            ...
 59     1386.106697     1522.439297       0.266746       0.733254
 60     1616.839430     1364.386238       0.751806       0.248194
 61     1483.856320     1567.480862       0.333496       0.666504
 62     1543.070177     1689.314175       0.255232       0.744768
 63     1474.911173     1413.984855       0.486148       0.513852

    simulated_winner
 0                TB
 1               CLE
 2               CIN
 3               HOU
 4               JAX
 ..              ...
 59              DAL
 60              PHI
 61              BAL
 62              SEA
 63               TB

 [64 rows x 10 columns],
 'sim_path': [None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'PHI',
  'MIA',
  'CIN',
  'JAX']}

In [16]:
## example of simulated season number
many_season_simulation[0]['sim']

1

In [17]:
## example of output of each game in simulated season
many_season_simulation[0]['sim_games']

,week,home_team,away_team,home_elo_before,away_elo_before,home_elo_after,away_elo_after,home_win_prob,away_win_prob,simulated_winner
0,15,TB,ATL,1458.330000,1427.810000,1468.890093,1417.249907,0.471995,0.528005,TB
1,15,CHI,CLE,1499.420000,1368.950000,1487.144432,1381.225568,0.613778,0.386222,CLE
2,15,CIN,BAL,1474.080000,1550.970000,1487.578026,1537.471974,0.325099,0.674901,CIN
3,15,HOU,ARI,1561.410000,1391.820000,1568.097713,1385.132287,0.665614,0.334386,HOU
4,15,JAX,NYJ,1513.620000,1312.800000,1519.532623,1306.887377,0.704369,0.295631,JAX
...,...,...,...,...,...,...,...,...,...,...
59,18,NYG,DAL,1391.441613,1517.104381,1386.106697,1522.439297,0.266746,0.733254,DAL
60,18,PHI,WAS,1611.875542,1369.350126,1616.839430,1364.386238,0.751806,0.248194,PHI
61,18,PIT,BAL,1490.526244,1560.810938,1483.856320,1567.480862,0.333496,0.666504,BAL
62,18,SF,SEA,1548.174808,1684.209543,1543.070177,1689.314175,0.255232,0.744768,SEA
63,18,TB,CAR,1464.634135,1424.261893,1474.911173,1413.984855,0.486148,0.513852,TB

In [18]:
## example of optimal survivor path for simulated season
many_season_simulation[0]['sim_path']

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'PHI',
 'MIA',
 'CIN',
 'JAX']

In [19]:
def pull_path_from_sim(seasons_list):
    """
    Inputs:
        seasons_list: output of simulate_full_season_multiple

    Outputs: 
        dataframe: simulation number as index, each week is a column
            so 1 row for each simulation with the team selected for that week ina  column

    Methodology:
        Extract the best paths data.
        Then create dataframe of simulations to make for easier analysis
    """
    all_paths = []
    for i in range(len(seasons_list)):
        sim_path = seasons_list[i]['sim_path']
        all_paths.append(sim_path)
    paths_df = pd.DataFrame(all_paths)
    paths_df.index = [f'sim_{i+1}' for i in range(len(all_paths))]
    paths_df.columns = [f'week_{i}' for i in range(paths_df.shape[1])]
    paths_df.drop('week_0', axis=1, inplace=True)

    return paths_df

In [20]:
many_season_simulation_paths = pull_path_from_sim(many_season_simulation)
many_season_simulation_paths

,week_1,week_2,week_3,week_4,week_5,week_6,week_7,week_8,week_9,week_10,week_11,week_12,week_13,week_14,week_15,week_16,week_17,week_18
sim_1,None,None,None,None,None,None,None,None,None,None,None,None,None,None,PHI,MIA,CIN,JAX
sim_2,None,None,None,None,None,None,None,None,None,None,None,None,None,None,PHI,HOU,CIN,JAX
sim_3,None,None,None,None,None,None,None,None,None,None,None,None,None,None,PHI,NO,CIN,JAX
sim_4,None,None,None,None,None,None,None,None,None,None,None,None,None,None,PHI,HOU,CIN,JAX
sim_5,None,None,None,None,None,None,None,None,None,None,None,None,None,None,PHI,HOU,LV,JAX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
sim_96,None,None,None,None,None,None,None,None,None,None,None,None,None,None,PHI,TEN,CIN,TB
sim_97,None,None,None,None,None,None,None,None,None,None,None,None,None,None,PHI,HOU,LAC,TB
sim_98,None,None,None,None,None,None,None,None,None,None,None,None,None,None,PHI,HOU,CIN,JAX
sim_99,None,None,None,None,None,None,None,None,None,None,None,None,None,None,SF,HOU,CIN,PHI
sim_100,None,None,None,None,None,None,None,None,None,None,None,None,None,None,PHI,HOU,TEN,JAX

## Running Simulations And Analysis

In [22]:
## week 1 picks over simulations
simulated_data_home_elo_before = simulate_full_season_multiple(teams_df.copy(), schedule_df.copy(), K, HFA, simulations=10000, seed = starting_seed, win_metric='home_elo_before')
simulated_paths_home_elo_before = pull_path_from_sim(simulated_data_home_elo_before)
simulated_paths_home_elo_before.value_counts('week_15')

week_15
PHI    5128
SF     2401
JAX    1395
HOU     454
DAL     322
CHI     183
TB       39
CIN      31
NYG      27
NO       10
MIA       5
MIN       3
LAC       2
Name: count, dtype: int64

In [23]:
## exmaple simulation
simulated_single_path_home_elo_before = simulated_paths_home_elo_before.iloc[[0]]
simulated_single_path_home_elo_before

,week_1,week_2,week_3,week_4,week_5,week_6,week_7,week_8,week_9,week_10,week_11,week_12,week_13,week_14,week_15,week_16,week_17,week_18
sim_1,None,None,None,None,None,None,None,None,None,None,None,None,None,None,HOU,CHI,LAC,PHI

In [24]:
## week 1 picks over simulations
simulated_data_home_win_prob = simulate_full_season_multiple(teams_df.copy(), schedule_df.copy(), K, HFA, simulations=10000, seed = 1, win_metric='home_win_prob')
simulated_paths_home_win_prob = pull_path_from_sim(simulated_data_home_win_prob)
simulated_paths_home_win_prob.value_counts('week_15')

week_15
PHI    7727
SF     1782
JAX     262
CHI     121
HOU      45
DAL      39
TB       12
NYG       6
CAR       4
NO        2
Name: count, dtype: int64

In [25]:
## exmaple simulation
simulated_sinlge_path_home_win_prob = simulated_paths_home_win_prob.iloc[[0]]
simulated_sinlge_path_home_win_prob

,week_1,week_2,week_3,week_4,week_5,week_6,week_7,week_8,week_9,week_10,week_11,week_12,week_13,week_14,week_15,week_16,week_17,week_18
sim_1,None,None,None,None,None,None,None,None,None,None,None,None,None,None,PHI,MIA,CIN,JAX

In [26]:
## week 1 picks over simulations
simulated_data_home_elo_difference = simulate_full_season_multiple(teams_df.copy(), schedule_df.copy(), K, HFA, simulations=10000, seed = 1, win_metric='home_elo_difference')
simulated_paths_home_elo_difference = pull_path_from_sim(simulated_data_home_elo_difference)
simulated_paths_home_elo_difference.value_counts('week_15')

week_15
PHI    7727
SF     1782
JAX     262
CHI     121
HOU      45
DAL      39
TB       12
NYG       6
CAR       4
NO        2
Name: count, dtype: int64

In [27]:
## exmaple simulation
simulated_sinlge_path_home_elo_difference = simulated_paths_home_elo_difference.iloc[[0]]
simulated_sinlge_path_home_elo_difference

,week_1,week_2,week_3,week_4,week_5,week_6,week_7,week_8,week_9,week_10,week_11,week_12,week_13,week_14,week_15,week_16,week_17,week_18
sim_1,None,None,None,None,None,None,None,None,None,None,None,None,None,None,PHI,MIA,CIN,JAX

In [28]:
simulated_paths_home_elo_before.value_counts('week_16')

week_16
HOU    6031
DAL    1599
CHI     689
MIA     546
CAR     399
NYG     289
NO      189
LAC      85
CLE      67
SF       37
TEN      28
JAX      17
PHI      14
CIN       8
TB        2
Name: count, dtype: int64

In [29]:
simulated_paths_home_win_prob.value_counts('week_16')

week_16
HOU    7333
NO     1238
DAL     655
NYG     231
MIA     173
CAR     164
TB       69
CHI      56
CLE      23
TEN      20
CIN      11
PHI      11
ATL      10
MIN       5
SF        1
Name: count, dtype: int64

In [30]:
simulated_paths_home_elo_difference.value_counts('week_16')

week_16
HOU    7333
NO     1238
DAL     655
NYG     231
MIA     173
CAR     164
TB       69
CHI      56
CLE      23
TEN      20
CIN      11
PHI      11
ATL      10
MIN       5
SF        1
Name: count, dtype: int64