## Imports

In [19]:
import pandas as pd
import numpy as np
import nfl_data_py as nfl

## Data And Parameters

In [20]:
## modeling input paramters
K = 20  ##max elo change per game
HFA = 50  ##home field advantage
num_simulations = 10000
starting_seed = 1

In [21]:
## game level data
seasons = [2025]
schedule_df = nfl.import_schedules(years=seasons)
schedule_df = schedule_df[schedule_df['game_type']=='REG']
schedule_df=schedule_df[['week','away_team', 'home_team','result']]

In [22]:
## Remove already used weeks
schedule_df = schedule_df[schedule_df['week']!=1]
schedule_df = schedule_df[schedule_df['week']!=2]
schedule_df = schedule_df[schedule_df['week']!=3]
schedule_df = schedule_df[schedule_df['week']!=4]
schedule_df = schedule_df[schedule_df['week']!=5]
schedule_df = schedule_df[schedule_df['week']!=6]
schedule_df = schedule_df[schedule_df['week']!=7]
schedule_df = schedule_df[schedule_df['week']!=8]
schedule_df = schedule_df[schedule_df['week']!=9]
schedule_df = schedule_df[schedule_df['week']!=10]

In [23]:
## elo data
elo = pd.read_csv('elo_2025_week11.csv')  ## elo pulled from https://www.nfeloapp.com/nfl-power-ratings/
teams_df = elo.copy()
teams_df = teams_df[['Team', 'nfelo']]
#make team names consistent
teams_df['Team'] = teams_df['Team'].replace({'LAR': 'LA', 'OAK': 'LV'})

## Function Definitions

In [24]:
def simulate_full_season(teams_df=teams_df.copy(), schedule_df=schedule_df.copy(), K=K, HFA=HFA, seed=starting_seed):
    """
    Input:
        teams_df: elo and team name
        schedule_df: week, home_team, away_team
        K: elo change per game
        HFA: home field advantage
        seed: for randomization

    Output:
        Dataframe: 1 row for each game throughout the entire season
            week. home_team, away_team, home_elo_before, away_elo_before, home_elo_after, away_elo_after, home_win_prob, away_win_prob, simulated_winner

    Methodology:
        Generates a record for each game.  Generates odds of each team winning, and simulates a winner based on those odds
        Updates ELO for both teams after the game, so they can be used in future games, allowing sull season to be simulated at a time
    """
    np.random.seed(seed)
    elo_ratings = teams_df.set_index('Team')['nfelo'].to_dict()
    all_game_results = []

    for week in sorted(schedule_df['week'].unique()):
        week_games = schedule_df[schedule_df['week'] == week]

        for df_index, df_game in week_games.iterrows():
            home_elo = elo_ratings[df_game['home_team']]
            away_elo = elo_ratings[df_game['away_team']]

            home_prob = 1/(1+10 **((away_elo-home_elo+HFA)/400))

            #simulate a winner
            winner = df_game['home_team'] if np.random.rand() < home_prob else df_game['away_team']

            if winner==df_game['home_team']:
                new_home_elo = home_elo + K * (1-home_prob)
                new_away_elo = away_elo + K * (home_prob-1)
            else:
                new_home_elo = home_elo + K * (0-home_prob)
                new_away_elo = away_elo + K * (home_prob-0)
            
            elo_ratings[df_game['home_team']] = new_home_elo
            elo_ratings[df_game['away_team']] = new_away_elo

            all_game_results.append({
                'week': week,
                'home_team': df_game['home_team'],
                'away_team': df_game['away_team'],
                'home_elo_before': home_elo,
                'away_elo_before': away_elo,
                'home_elo_after': new_home_elo,
                'away_elo_after': new_away_elo,
                'home_win_prob': home_prob,
                'away_win_prob': (1-home_prob),
                'simulated_winner': winner})
            
    return pd.DataFrame(all_game_results)

In [25]:
single_season_simulation = simulate_full_season(teams_df,schedule_df, 20, 50, 5)
single_season_simulation.head(5)

,week,home_team,away_team,home_elo_before,away_elo_before,home_elo_after,away_elo_after,home_win_prob,away_win_prob,simulated_winner
0,11,NE,NYJ,1516.81,1392.29,1524.697439,1384.402561,0.605628,0.394372,NE
1,11,MIA,WAS,1391.26,1418.36,1383.443393,1426.176607,0.390830,0.609170,WAS
2,11,ATL,CAR,1445.81,1384.61,1455.487750,1374.932250,0.516113,0.483887,ATL
3,11,BUF,TB,1608.40,1516.36,1597.195862,1527.564138,0.560207,0.439793,TB
4,11,JAX,LAC,1434.99,1535.49,1429.069703,1541.410297,0.296015,0.703985,LAC

In [26]:
def global_survivor_path(simulated_season_df, win_metric='home_win_prob'):
    """
    Input:
        simulated_season_df: output of simulate_full_season
        win_metric: what metric you want to use to calculate path
            home_win_prob: maximze win probability, emphasis on home
            home_elo_difference: maximize elo difference between teams, emphasis on home
            home_elo_before: maximize elo before game.  emphasis on home
    
    Output:
        list of teams in order of week selected.  None is first entry for week 0

    Methodology:
        Scans the season looking for the highest value of metric.
        Then that winning team is added to used_teams, and that week is dropped from data
        Then keep iterating through until a team is selected for each week

    """
    survivor_path = [None] * (19)
    used_teams = set()
    used_teams.update(['WAS', 'BAL', 'SEA', 'BUF', 'ARI', 'GB', 'KC', 'IND', 'LAR', 'DET'])
    remaining_games = simulated_season_df.copy()

    while remaining_games['week'].nunique()>0:
        if win_metric == 'home_win_prob':
            iteration_df = remaining_games.copy()
            iteration_df = iteration_df[~iteration_df['simulated_winner'].isin(used_teams)]
            iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['home_team']]
            if not iteration_df_1.empty:
                iteration_df_2 = iteration_df_1[iteration_df_1['home_win_prob'] == iteration_df_1['home_win_prob'].max()]
                win_team = iteration_df_2['home_team'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]
            else:
                iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['away_team']]
                iteration_df_2 = iteration_df[iteration_df['away_win_prob'] == iteration_df['away_win_prob'].max()]
                win_team = iteration_df_2['away_win_prob'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]

        
        if win_metric == 'home_elo_difference':
            iteration_df = remaining_games.copy()
            iteration_df = iteration_df[~iteration_df['simulated_winner'].isin(used_teams)]
            iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['home_team']]
            if not iteration_df_1.empty:
                iteration_df_2 = iteration_df_1[(iteration_df_1['home_elo_before']-iteration_df_1['away_elo_before']) == (iteration_df_1['home_elo_before'] - iteration_df_1['away_elo_before']).max()]
                win_team = iteration_df_2['home_team'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]
            else:
                iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['away_team']]
                iteration_df_2 = iteration_df_1[(iteration_df_1['home_elo_before']-iteration_df_1['away_elo_before']) == (iteration_df_1['home_elo_before'] - iteration_df_1['away_elo_before']).min()]
                win_team = iteration_df_2['away_win_prob'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]
        
        if win_metric == 'home_elo_before':
            iteration_df = remaining_games.copy()
            iteration_df = iteration_df[~iteration_df['simulated_winner'].isin(used_teams)]
            iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['home_team']]
            if not iteration_df_1.empty:
                iteration_df_2 = iteration_df_1[iteration_df_1['home_elo_before'] == iteration_df_1['home_elo_before'].max()]
                win_team = iteration_df_2['home_team'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]
            else:
                iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['away_team']]
                iteration_df_2 = iteration_df_1[iteration_df_1['away_elo_before'] == iteration_df_1['away_elo_before'].max()]
                win_team = iteration_df_2['away_win_prob'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]

    return survivor_path

In [27]:
single_season_path = global_survivor_path(single_season_simulation, 'home_win_prob')
single_season_path

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'PIT',
 'CHI',
 'NE',
 'TB',
 'SF',
 'HOU',
 'TEN',
 'LA']

In [28]:
def simulate_full_season_multiple(teams_df=teams_df.copy(), schedule_df=schedule_df.copy(), K=K, HFA=HFA, simulations=num_simulations, seed = starting_seed, win_metric='home_win_prob'):
    """
    Input:
        teams_df: elo and team name
        schedule_df: week, home_team, away_team
        K: elo change per game
        HFA: home field advantage
        simulations: number of seasons you want to simulate
        seed: for randomization
            win_metric: what metric you want to use to calculate path
            home_win_prob: maximze win probability, emphasis on home
            home_elo_difference: maximize elo difference between teams, emphasis on home
            home_elo_before: maximize elo before game.  emphasis on home

    Output:
        List for each season simualted: contains all game results and best path
            Dictionary 'sim': get the number of the simulation
            Dictionary 'sim_games': get the game data for each simulated game.  Same output as simulate_full_season
            Dictionary 'sim_path': list of the teams selected by week.  Same output as global_survivor_path
    Methodology:
        Runs the simulate_full_season function and then finds the best path for that season global_survivor_path
        Increase the seed by 1, so each simulation is of a different season
    """
    all_season_results = []
    np.random.seed()

    for sim in range(simulations):
        sim_seed = seed+sim
        sim_games = simulate_full_season(teams_df.copy(), schedule_df.copy(), K, HFA, seed=sim_seed)
        sim_path = global_survivor_path(sim_games.copy(), win_metric=win_metric)

        all_season_results.append({
            'sim': sim+1,
            'sim_games': sim_games,
            'sim_path': sim_path})
    return all_season_results

In [29]:
many_season_simulation = simulate_full_season_multiple(teams_df, schedule_df, 20, 50, 100, 1, 'home_win_prob')

In [30]:
## example single season output
many_season_simulation[0]

{'sim': 1,
 'sim_games':      week home_team away_team  home_elo_before  away_elo_before  \
 0      11        NE       NYJ      1516.810000      1392.290000
 1      11       MIA       WAS      1391.260000      1418.360000
 2      11       ATL       CAR      1445.810000      1384.610000
 3      11       BUF        TB      1608.400000      1516.360000
 4      11       JAX       LAC      1434.990000      1535.490000
 ..    ...       ...       ...              ...              ...
 118    18       NYG       DAL      1373.336677      1463.782238
 119    18       PHI       WAS      1627.720611      1427.409576
 120    18       PIT       BAL      1516.216736      1636.508825
 121    18        SF       SEA      1526.586059      1628.117099
 122    18        TB       CAR      1515.531875      1365.436450

      home_elo_after  away_elo_after  home_win_prob  away_win_prob  \
 0       1524.697439     1384.402561       0.605628       0.394372
 1       1383.443393     1426.176607       0.390830       0.609170
 2       1455.487750     1374.932250       0.516113       0.483887
 3       1617.195862     1507.564138       0.560207       0.439793
 4       1449.069703     1521.410297       0.296015       0.703985
 ..              ...             ...            ...            ...
 118     1367.172343     1469.946572       0.308217       0.691783
 119     1633.645443     1421.484745       0.703758       0.296242
 120     1530.760012     1621.965549       0.272836       0.727164
 121     1540.690468     1614.012689       0.294780       0.705220
 122     1522.728044     1358.240280       0.640192       0.359808

     simulated_winner
 0                 NE
 1                WAS
 2                ATL
 3                BUF
 4                JAX
 ..               ...
 118              DAL
 119              PHI
 120              PIT
 121               SF
 122               TB

 [123 rows x 10 columns],
 'sim_path': [None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'NE',
  'LA',
  'DAL',
  'TB',
  'SF',
  'DEN',
  'LV',
  'JAX']}

In [31]:
## example of simulated season number
many_season_simulation[0]['sim']

1

In [32]:
## example of output of each game in simulated season
many_season_simulation[0]['sim_games']

,week,home_team,away_team,home_elo_before,away_elo_before,home_elo_after,away_elo_after,home_win_prob,away_win_prob,simulated_winner
0,11,NE,NYJ,1516.810000,1392.290000,1524.697439,1384.402561,0.605628,0.394372,NE
1,11,MIA,WAS,1391.260000,1418.360000,1383.443393,1426.176607,0.390830,0.609170,WAS
2,11,ATL,CAR,1445.810000,1384.610000,1455.487750,1374.932250,0.516113,0.483887,ATL
3,11,BUF,TB,1608.400000,1516.360000,1617.195862,1507.564138,0.560207,0.439793,BUF
4,11,JAX,LAC,1434.990000,1535.490000,1449.069703,1521.410297,0.296015,0.703985,JAX
...,...,...,...,...,...,...,...,...,...,...
118,18,NYG,DAL,1373.336677,1463.782238,1367.172343,1469.946572,0.308217,0.691783,DAL
119,18,PHI,WAS,1627.720611,1427.409576,1633.645443,1421.484745,0.703758,0.296242,PHI
120,18,PIT,BAL,1516.216736,1636.508825,1530.760012,1621.965549,0.272836,0.727164,PIT
121,18,SF,SEA,1526.586059,1628.117099,1540.690468,1614.012689,0.294780,0.705220,SF
122,18,TB,CAR,1515.531875,1365.436450,1522.728044,1358.240280,0.640192,0.359808,TB

In [33]:
## example of optimal survivor path for simulated season
many_season_simulation[0]['sim_path']

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'NE',
 'LA',
 'DAL',
 'TB',
 'SF',
 'DEN',
 'LV',
 'JAX']

In [34]:
def pull_path_from_sim(seasons_list):
    """
    Inputs:
        seasons_list: output of simulate_full_season_multiple

    Outputs: 
        dataframe: simulation number as index, each week is a column
            so 1 row for each simulation with the team selected for that week ina  column

    Methodology:
        Extract the best paths data.
        Then create dataframe of simulations to make for easier analysis
    """
    all_paths = []
    for i in range(len(seasons_list)):
        sim_path = seasons_list[i]['sim_path']
        all_paths.append(sim_path)
    paths_df = pd.DataFrame(all_paths)
    paths_df.index = [f'sim_{i+1}' for i in range(len(all_paths))]
    paths_df.columns = [f'week_{i}' for i in range(paths_df.shape[1])]
    paths_df.drop('week_0', axis=1, inplace=True)

    return paths_df

In [35]:
many_season_simulation_paths = pull_path_from_sim(many_season_simulation)
many_season_simulation_paths

,week_1,week_2,week_3,week_4,week_5,week_6,week_7,week_8,week_9,week_10,week_11,week_12,week_13,week_14,week_15,week_16,week_17,week_18
sim_1,None,None,None,None,None,None,None,None,None,None,NE,LA,DAL,TB,SF,DEN,LV,JAX
sim_2,None,None,None,None,None,None,None,None,None,None,MIA,LA,NE,CLE,SF,DEN,NO,PHI
sim_3,None,None,None,None,None,None,None,None,None,None,NE,SF,LAC,TB,PHI,NO,LV,LA
sim_4,None,None,None,None,None,None,None,None,None,None,PIT,LV,LAC,TB,SF,HOU,CIN,LA
sim_5,None,None,None,None,None,None,None,None,None,None,PIT,CHI,NE,TB,SF,HOU,TEN,LA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
sim_96,None,None,None,None,None,None,None,None,None,None,NE,SF,LAC,NYJ,PHI,HOU,MIA,LA
sim_97,None,None,None,None,None,None,None,None,None,None,ATL,CHI,NE,TB,SF,HOU,LV,LA
sim_98,None,None,None,None,None,None,None,None,None,None,PIT,LV,PHI,TB,SF,HOU,CIN,LA
sim_99,None,None,None,None,None,None,None,None,None,None,PIT,SF,LAC,CLE,PHI,DEN,CIN,LA
sim_100,None,None,None,None,None,None,None,None,None,None,ATL,CHI,NE,TB,SF,HOU,CLE,LA

## Running Simulations And Analysis

In [46]:
## week 1 picks over simulations
simulated_data_home_elo_before = simulate_full_season_multiple(teams_df.copy(), schedule_df.copy(), K, HFA, simulations=10000, seed = starting_seed, win_metric='home_elo_before')
simulated_paths_home_elo_before = pull_path_from_sim(simulated_data_home_elo_before)
simulated_paths_home_elo_before.value_counts('week_11')

week_11
NE     3038
PIT    2027
DEN    1314
PHI     899
LA      798
ATL     601
MIN     601
JAX     196
MIA     125
NYG      85
LV       71
CLE      69
HOU      42
LAC      33
CHI      29
TEN      23
SF       21
DAL      15
TB       13
Name: count, dtype: int64

In [37]:
## exmaple simulation
simulated_single_path_home_elo_before = simulated_paths_home_elo_before.iloc[[0]]
simulated_single_path_home_elo_before

,week_1,week_2,week_3,week_4,week_5,week_6,week_7,week_8,week_9,week_10,week_11,week_12,week_13,week_14,week_15,week_16,week_17,week_18
sim_1,None,None,None,None,None,None,None,None,None,None,NE,LA,DAL,TB,SF,DEN,ATL,PHI

In [38]:
## week 1 picks over simulations
simulated_data_home_win_prob = simulate_full_season_multiple(teams_df.copy(), schedule_df.copy(), K, HFA, simulations=10000, seed = 1, win_metric='home_win_prob')
simulated_paths_home_win_prob = pull_path_from_sim(simulated_data_home_win_prob)
simulated_paths_home_win_prob.value_counts('week_11')

week_11
NE     4976
PIT    2627
ATL    1169
MIA     401
MIN     284
DEN      97
JAX      80
LA       75
DAL      69
PHI      63
HOU      48
LV       35
NYG      25
CLE      21
TEN      13
LAC       7
CHI       4
CAR       3
SF        3
Name: count, dtype: int64

In [39]:
## exmaple simulation
simulated_sinlge_path_home_win_prob = simulated_paths_home_win_prob.iloc[[0]]
simulated_sinlge_path_home_win_prob

,week_1,week_2,week_3,week_4,week_5,week_6,week_7,week_8,week_9,week_10,week_11,week_12,week_13,week_14,week_15,week_16,week_17,week_18
sim_1,None,None,None,None,None,None,None,None,None,None,NE,LA,DAL,TB,SF,DEN,LV,JAX

In [40]:
## week 1 picks over simulations
simulated_data_home_elo_difference = simulate_full_season_multiple(teams_df.copy(), schedule_df.copy(), K, HFA, simulations=10000, seed = 1, win_metric='home_elo_difference')
simulated_paths_home_elo_difference = pull_path_from_sim(simulated_data_home_elo_difference)
simulated_paths_home_elo_difference.value_counts('week_11')

week_11
NE     4976
PIT    2627
ATL    1169
MIA     401
MIN     284
DEN      97
JAX      80
LA       75
DAL      69
PHI      63
HOU      48
LV       35
NYG      25
CLE      21
TEN      13
LAC       7
CHI       4
CAR       3
SF        3
Name: count, dtype: int64

In [41]:
## exmaple simulation
simulated_sinlge_path_home_elo_difference = simulated_paths_home_elo_difference.iloc[[0]]
simulated_sinlge_path_home_elo_difference

,week_1,week_2,week_3,week_4,week_5,week_6,week_7,week_8,week_9,week_10,week_11,week_12,week_13,week_14,week_15,week_16,week_17,week_18
sim_1,None,None,None,None,None,None,None,None,None,None,NE,LA,DAL,TB,SF,DEN,LV,JAX

In [42]:
simulated_paths_home_elo_difference.value_counts('week_12')

week_12
CHI    2885
SF     1742
LA     1732
LV     1165
NO      492
PHI     443
CIN     413
ATL     406
DAL     380
HOU     247
TEN      49
NE       27
CLE       9
JAX       6
PIT       4
Name: count, dtype: int64

In [43]:
simulated_paths_home_elo_before.value_counts('week_12')

week_12
LA     2866
SF     2187
CHI    1410
HOU    1177
DAL     631
LV      502
CIN     437
NO      235
PIT     178
NE      177
TB       53
PHI      42
MIN      38
TEN      33
ATL      28
JAX       6
Name: count, dtype: int64

In [44]:
simulated_paths_home_win_prob.value_counts('week_12')

week_12
CHI    2885
SF     1742
LA     1732
LV     1165
NO      492
PHI     443
CIN     413
ATL     406
DAL     380
HOU     247
TEN      49
NE       27
CLE       9
JAX       6
PIT       4
Name: count, dtype: int64

In [45]:
simulated_paths_home_elo_difference.value_counts('week_12')

week_12
CHI    2885
SF     1742
LA     1732
LV     1165
NO      492
PHI     443
CIN     413
ATL     406
DAL     380
HOU     247
TEN      49
NE       27
CLE       9
JAX       6
PIT       4
Name: count, dtype: int64