## Imports

In [1]:
import pandas as pd
import numpy as np
import nfl_data_py as nfl

## Data And Parameters

In [2]:
## modeling input paramters
K = 20  ##max elo change per game
HFA = 50  ##home field advantage
num_simulations = 10000
starting_seed = 1

In [3]:
## game level data
seasons = [2025]
schedule_df = nfl.import_schedules(years=seasons)
schedule_df = schedule_df[schedule_df['game_type']=='REG']
schedule_df=schedule_df[['week','away_team', 'home_team','result']]

In [4]:
## Remove already used weeks
schedule_df = schedule_df[schedule_df['week']!=1]
schedule_df = schedule_df[schedule_df['week']!=2]

In [5]:
## elo data
elo = pd.read_csv('elo_2025_week3.csv')  ## elo pulled from https://www.nfeloapp.com/nfl-power-ratings/
teams_df = elo.copy()
teams_df = teams_df[['Team', 'nfelo']]
#make team names consistent
teams_df['Team'] = teams_df['Team'].replace({'LAR': 'LA', 'OAK': 'LV'})

## Function Definitions

In [6]:
def simulate_full_season(teams_df=teams_df.copy(), schedule_df=schedule_df.copy(), K=K, HFA=HFA, seed=starting_seed):
    """
    Input:
        teams_df: elo and team name
        schedule_df: week, home_team, away_team
        K: elo change per game
        HFA: home field advantage
        seed: for randomization

    Output:
        Dataframe: 1 row for each game throughout the entire season
            week. home_team, away_team, home_elo_before, away_elo_before, home_elo_after, away_elo_after, home_win_prob, away_win_prob, simulated_winner

    Methodology:
        Generates a record for each game.  Generates odds of each team winning, and simulates a winner based on those odds
        Updates ELO for both teams after the game, so they can be used in future games, allowing sull season to be simulated at a time
    """
    np.random.seed(seed)
    elo_ratings = teams_df.set_index('Team')['nfelo'].to_dict()
    all_game_results = []

    for week in sorted(schedule_df['week'].unique()):
        week_games = schedule_df[schedule_df['week'] == week]

        for df_index, df_game in week_games.iterrows():
            home_elo = elo_ratings[df_game['home_team']]
            away_elo = elo_ratings[df_game['away_team']]

            home_prob = 1/(1+10 **((away_elo-home_elo+HFA)/400))

            #simulate a winner
            winner = df_game['home_team'] if np.random.rand() < home_prob else df_game['away_team']

            if winner==df_game['home_team']:
                new_home_elo = home_elo + K * (1-home_prob)
                new_away_elo = away_elo + K * (home_prob-1)
            else:
                new_home_elo = home_elo + K * (0-home_prob)
                new_away_elo = away_elo + K * (home_prob-0)
            
            elo_ratings[df_game['home_team']] = new_home_elo
            elo_ratings[df_game['away_team']] = new_away_elo

            all_game_results.append({
                'week': week,
                'home_team': df_game['home_team'],
                'away_team': df_game['away_team'],
                'home_elo_before': home_elo,
                'away_elo_before': away_elo,
                'home_elo_after': new_home_elo,
                'away_elo_after': new_away_elo,
                'home_win_prob': home_prob,
                'away_win_prob': (1-home_prob),
                'simulated_winner': winner})
            
    return pd.DataFrame(all_game_results)

In [7]:
single_season_simulation = simulate_full_season(teams_df,schedule_df, 20, 50, 5)
single_season_simulation.head(5)

,week,home_team,away_team,home_elo_before,away_elo_before,home_elo_after,away_elo_after,home_win_prob,away_win_prob,simulated_winner
0,3,BUF,MIA,1635.52,1443.82,1641.653583,1437.686417,0.693321,0.306679,BUF
1,3,CAR,ATL,1375.71,1485.68,1370.014352,1491.375648,0.284782,0.715218,ATL
2,3,CLE,GB,1386.04,1606.10,1382.551515,1609.588485,0.174424,0.825576,GB
3,3,JAX,HOU,1471.61,1492.32,1463.617556,1500.312444,0.399622,0.600378,HOU
4,3,MIN,CIN,1514.00,1468.86,1524.139873,1458.720127,0.493006,0.506994,MIN

In [8]:
def global_survivor_path(simulated_season_df, win_metric='home_win_prob'):
    """
    Input:
        simulated_season_df: output of simulate_full_season
        win_metric: what metric you want to use to calculate path
            home_win_prob: maximze win probability, emphasis on home
            home_elo_difference: maximize elo difference between teams, emphasis on home
            home_elo_before: maximize elo before game.  emphasis on home
    
    Output:
        list of teams in order of week selected.  None is first entry for week 0

    Methodology:
        Scans the season looking for the highest value of metric.
        Then that winning team is added to used_teams, and that week is dropped from data
        Then keep iterating through until a team is selected for each week

    """
    survivor_path = [None] * (19)
    used_teams = set()
    remaining_games = simulated_season_df.copy()

    while remaining_games['week'].nunique()>0:
        if win_metric == 'home_win_prob':
            iteration_df = remaining_games.copy()
            iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['home_team']]
            if not iteration_df_1.empty:
                iteration_df_2 = iteration_df_1[iteration_df_1['home_win_prob'] == iteration_df_1['home_win_prob'].max()]
                win_team = iteration_df_2['home_team'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]
            else:
                iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['away_team']]
                iteration_df_2 = iteration_df[iteration_df['away_win_prob'] == iteration_df['away_win_prob'].max()]
                win_team = iteration_df_2['away_win_prob'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]

        
        if win_metric == 'home_elo_difference':
            iteration_df = remaining_games.copy()
            iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['home_team']]
            if not iteration_df_1.empty:
                iteration_df_2 = iteration_df_1[(iteration_df_1['home_elo_before']-iteration_df_1['away_elo_before']) == (iteration_df_1['home_elo_before'] - iteration_df_1['away_elo_before']).max()]
                win_team = iteration_df_2['home_team'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]
            else:
                iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['away_team']]
                iteration_df_2 = iteration_df_1[(iteration_df_1['home_elo_before']-iteration_df_1['away_elo_before']) == (iteration_df_1['home_elo_before'] - iteration_df_1['away_elo_before']).min()]
                win_team = iteration_df_2['away_win_prob'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]
        
        if win_metric == 'home_elo_before':
            iteration_df = remaining_games.copy()
            iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['home_team']]
            if not iteration_df_1.empty:
                iteration_df_2 = iteration_df_1[iteration_df_1['home_elo_before'] == iteration_df_1['home_elo_before'].max()]
                win_team = iteration_df_2['home_team'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]
            else:
                iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['away_team']]
                iteration_df_2 = iteration_df_1[iteration_df_1['away_elo_before'] == iteration_df_1['away_elo_before'].max()]
                win_team = iteration_df_2['away_win_prob'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]

    return survivor_path

In [9]:
single_season_path = global_survivor_path(single_season_simulation, 'home_win_prob')
single_season_path

[None,
 None,
 None,
 'WAS',
 'BUF',
 'ARI',
 'PIT',
 'KC',
 'IND',
 'GB',
 'DEN',
 'LA',
 'BAL',
 'LAC',
 'JAX',
 'PHI',
 'HOU',
 'TEN',
 'TB']

In [10]:
def simulate_full_season_multiple(teams_df=teams_df.copy(), schedule_df=schedule_df.copy(), K=K, HFA=HFA, simulations=num_simulations, seed = starting_seed, win_metric='home_win_prob'):
    """
    Input:
        teams_df: elo and team name
        schedule_df: week, home_team, away_team
        K: elo change per game
        HFA: home field advantage
        simulations: number of seasons you want to simulate
        seed: for randomization
            win_metric: what metric you want to use to calculate path
            home_win_prob: maximze win probability, emphasis on home
            home_elo_difference: maximize elo difference between teams, emphasis on home
            home_elo_before: maximize elo before game.  emphasis on home

    Output:
        List for each season simualted: contains all game results and best path
            Dictionary 'sim': get the number of the simulation
            Dictionary 'sim_games': get the game data for each simulated game.  Same output as simulate_full_season
            Dictionary 'sim_path': list of the teams selected by week.  Same output as global_survivor_path
    Methodology:
        Runs the simulate_full_season function and then finds the best path for that season global_survivor_path
        Increase the seed by 1, so each simulation is of a different season
    """
    all_season_results = []
    np.random.seed()

    for sim in range(simulations):
        sim_seed = seed+sim
        sim_games = simulate_full_season(teams_df.copy(), schedule_df.copy(), K, HFA, seed=sim_seed)
        sim_path = global_survivor_path(sim_games.copy(), win_metric=win_metric)

        all_season_results.append({
            'sim': sim+1,
            'sim_games': sim_games,
            'sim_path': sim_path})
    return all_season_results

In [11]:
many_season_simulation = simulate_full_season_multiple(teams_df, schedule_df, 20, 50, 100, 1, 'home_win_prob')

In [12]:
## example single season output
many_season_simulation[0]

{'sim': 1,
 'sim_games':      week home_team away_team  home_elo_before  away_elo_before  \
 0       3       BUF       MIA      1635.520000      1443.820000
 1       3       CAR       ATL      1375.710000      1485.680000
 2       3       CLE        GB      1386.040000      1606.100000
 3       3       JAX       HOU      1471.610000      1492.320000
 4       3       MIN       CIN      1514.000000      1468.860000
 ..    ...       ...       ...              ...              ...
 235    18       NYG       DAL      1436.746043      1480.662098
 236    18       PHI       WAS      1643.849906      1499.597502
 237    18       PIT       BAL      1460.974786      1624.451861
 238    18        SF       SEA      1521.297628      1497.838138
 239    18        TB       CAR      1496.079769      1379.786882

      home_elo_after  away_elo_after  home_win_prob  away_win_prob  \
 0       1641.653583     1437.686417       0.693321       0.306679
 1       1370.014352     1491.375648       0.284782       0.715218
 2       1402.551515     1589.588485       0.174424       0.825576
 3       1483.617556     1480.312444       0.399622       0.600378
 4       1524.139873     1458.720127       0.493006       0.506994
 ..              ...             ...            ...            ...
 235     1429.385195     1488.022945       0.368042       0.631958
 236     1651.201749     1492.245659       0.632408       0.367592
 237     1456.447211     1628.979436       0.226379       0.773621
 238     1532.060043     1487.075723       0.461879       0.538121
 239     1484.194530     1391.672122       0.594262       0.405738

     simulated_winner
 0                BUF
 1                ATL
 2                CLE
 3                JAX
 4                MIN
 ..               ...
 235              DAL
 236              PHI
 237              BAL
 238               SF
 239              CAR

 [240 rows x 10 columns],
 'sim_path': [None,
  None,
  None,
  'JAX',
  'BUF',
  'NYJ',
  'LV',
  'DEN',
  'PHI',
  'GB',
  'CHI',
  'MIN',
  'BAL',
  'IND',
  'TB',
  'KC',
  'DET',
  'LAC',
  'ATL']}

In [13]:
## example of simulated season number
many_season_simulation[0]['sim']

1

In [14]:
## example of output of each game in simulated season
many_season_simulation[0]['sim_games']

,week,home_team,away_team,home_elo_before,away_elo_before,home_elo_after,away_elo_after,home_win_prob,away_win_prob,simulated_winner
0,3,BUF,MIA,1635.520000,1443.820000,1641.653583,1437.686417,0.693321,0.306679,BUF
1,3,CAR,ATL,1375.710000,1485.680000,1370.014352,1491.375648,0.284782,0.715218,ATL
2,3,CLE,GB,1386.040000,1606.100000,1402.551515,1589.588485,0.174424,0.825576,CLE
3,3,JAX,HOU,1471.610000,1492.320000,1483.617556,1480.312444,0.399622,0.600378,JAX
4,3,MIN,CIN,1514.000000,1468.860000,1524.139873,1458.720127,0.493006,0.506994,MIN
...,...,...,...,...,...,...,...,...,...,...
235,18,NYG,DAL,1436.746043,1480.662098,1429.385195,1488.022945,0.368042,0.631958,DAL
236,18,PHI,WAS,1643.849906,1499.597502,1651.201749,1492.245659,0.632408,0.367592,PHI
237,18,PIT,BAL,1460.974786,1624.451861,1456.447211,1628.979436,0.226379,0.773621,BAL
238,18,SF,SEA,1521.297628,1497.838138,1532.060043,1487.075723,0.461879,0.538121,SF
239,18,TB,CAR,1496.079769,1379.786882,1484.194530,1391.672122,0.594262,0.405738,CAR

In [15]:
## example of optimal survivor path for simulated season
many_season_simulation[0]['sim_path']

[None,
 None,
 None,
 'JAX',
 'BUF',
 'NYJ',
 'LV',
 'DEN',
 'PHI',
 'GB',
 'CHI',
 'MIN',
 'BAL',
 'IND',
 'TB',
 'KC',
 'DET',
 'LAC',
 'ATL']

In [16]:
def pull_path_from_sim(seasons_list):
    """
    Inputs:
        seasons_list: output of simulate_full_season_multiple

    Outputs: 
        dataframe: simulation number as index, each week is a column
            so 1 row for each simulation with the team selected for that week ina  column

    Methodology:
        Extract the best paths data.
        Then create dataframe of simulations to make for easier analysis
    """
    all_paths = []
    for i in range(len(seasons_list)):
        sim_path = seasons_list[i]['sim_path']
        all_paths.append(sim_path)
    paths_df = pd.DataFrame(all_paths)
    paths_df.index = [f'sim_{i+1}' for i in range(len(all_paths))]
    paths_df.columns = [f'week_{i}' for i in range(paths_df.shape[1])]
    paths_df.drop('week_0', axis=1, inplace=True)

    return paths_df

In [19]:
many_season_simulation_paths = pull_path_from_sim(many_season_simulation)
many_season_simulation_paths

,week_1,week_2,week_3,week_4,week_5,week_6,week_7,week_8,week_9,week_10,week_11,week_12,week_13,week_14,week_15,week_16,week_17,week_18
sim_1,None,None,JAX,BUF,NYJ,LV,DEN,PHI,GB,CHI,MIN,BAL,IND,TB,KC,DET,LAC,ATL
sim_2,None,None,SEA,BUF,LAC,LV,DEN,PHI,GB,CHI,ATL,BAL,NE,TB,SF,DET,PIT,CIN
sim_3,None,None,SEA,BUF,ARI,PIT,KC,CIN,LA,TB,NE,DET,MIA,JAX,PHI,BAL,LAC,ATL
sim_4,None,None,SEA,MIA,BAL,PIT,DEN,PHI,LA,GB,ARI,DET,LAC,TB,CHI,IND,KC,NE
sim_5,None,None,WAS,BUF,ARI,PIT,KC,IND,GB,DEN,LA,BAL,LAC,JAX,PHI,HOU,TEN,TB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
sim_96,None,None,BUF,DET,ARI,WAS,CHI,PHI,GB,LAC,LA,BAL,IND,KC,NO,DEN,SF,CIN
sim_97,None,None,SEA,BUF,ARI,PIT,CHI,BAL,LA,DEN,ATL,DET,LAC,GB,PHI,DAL,SF,CIN
sim_98,None,None,SEA,BUF,IND,PIT,KC,PHI,GB,CAR,MIN,BAL,LAC,TB,SF,DET,LV,ATL
sim_99,None,None,TB,DET,ARI,WAS,KC,IND,GB,DEN,ATL,BAL,LAC,CLE,SF,NO,TEN,BUF
sim_100,None,None,SEA,BUF,NO,GB,DEN,KC,LA,WAS,PIT,DET,LAC,JAX,PHI,BAL,NYJ,TB

## Running Simulations And Analysis

In [20]:
## week 1 picks over simulations
simulated_data_home_elo_before = simulate_full_season_multiple(teams_df.copy(), schedule_df.copy(), K, HFA, simulations=10000, seed = starting_seed, win_metric='home_elo_before')
simulated_paths_home_elo_before = pull_path_from_sim(simulated_data_home_elo_before)
simulated_paths_home_elo_before.value_counts('week_3')

week_3
TB     1681
SEA    1435
MIN    1417
PHI    1023
LAC     964
BAL     734
BUF     676
WAS     502
SF      417
JAX     353
CHI     284
NE      151
NYG      71
CAR      70
CLE      49
TEN      42
ARI      37
HOU      29
IND      16
LA       11
GB       11
KC       10
DEN       7
PIT       7
DET       1
DAL       1
ATL       1
Name: count, dtype: int64

In [21]:
## exmaple simulation
simulated_single_path_home_elo_before = simulated_paths_home_elo_before.iloc[[0]]
simulated_single_path_home_elo_before

,week_1,week_2,week_3,week_4,week_5,week_6,week_7,week_8,week_9,week_10,week_11,week_12,week_13,week_14,week_15,week_16,week_17,week_18
sim_1,None,None,LAC,KC,NYJ,BAL,DET,PHI,CIN,TB,DEN,GB,IND,CLE,LA,CAR,BUF,MIN

In [22]:
## week 1 picks over simulations
simulated_data_home_win_prob = simulate_full_season_multiple(teams_df.copy(), schedule_df.copy(), K, HFA, simulations=10000, seed = 1, win_metric='home_win_prob')
simulated_paths_home_win_prob = pull_path_from_sim(simulated_data_home_win_prob)
simulated_paths_home_win_prob.value_counts('week_3')

week_3
SEA    6111
WAS    1138
TB      876
MIN     542
BUF     407
JAX     156
SF      131
CHI     113
NE       91
LAC      88
CAR      68
PHI      63
KC       44
TEN      43
IND      31
NYG      29
CLE      21
GB       15
ATL      15
PIT       9
DAL       7
BAL       2
Name: count, dtype: int64

In [23]:
## exmaple simulation
simulated_sinlge_path_home_win_prob = simulated_paths_home_win_prob.iloc[[0]]
simulated_sinlge_path_home_win_prob

,week_1,week_2,week_3,week_4,week_5,week_6,week_7,week_8,week_9,week_10,week_11,week_12,week_13,week_14,week_15,week_16,week_17,week_18
sim_1,None,None,JAX,BUF,NYJ,LV,DEN,PHI,GB,CHI,MIN,BAL,IND,TB,KC,DET,LAC,ATL

In [ ]:
## week 1 picks over simulations
simulated_data_home_elo_difference = simulate_full_season_multiple(teams_df.copy(), schedule_df.copy(), K, HFA, simulations=10000, seed = 1, win_metric='home_elo_difference')
simulated_paths_home_elo_difference = pull_path_from_sim(simulated_data_home_elo_difference)
simulated_paths_home_elo_difference.value_counts('week_3')

In [ ]:
## exmaple simulation
simulated_sinlge_path_home_elo_difference = simulated_paths_home_elo_difference.iloc[[0]]
simulated_sinlge_path_home_elo_difference

,week_1,week_2,week_3,week_4,week_5,week_6,week_7,week_8,week_9,week_10,week_11,week_12,week_13,week_14,week_15,week_16,week_17,week_18
sim_1,None,BAL,SEA,BUF,ARI,LV,NYJ,PHI,GB,CHI,LA,DET,LAC,TB,SF,DEN,TEN,ATL