## Imports

In [1]:
import pandas as pd
import numpy as np
import nfl_data_py as nfl

## Data And Parameters

In [2]:
## modeling input paramters
K = 20  ##max elo change per game
HFA = 50  ##home field advantage
num_simulations = 10000
starting_seed = 1

In [3]:
## game level data
seasons = [2025]
schedule_df = nfl.import_schedules(years=seasons)
schedule_df = schedule_df[schedule_df['game_type']=='REG']
schedule_df=schedule_df[['week','away_team', 'home_team','result']]

In [4]:
## Remove already used weeks
schedule_df = schedule_df[schedule_df['week']!=1]
schedule_df = schedule_df[schedule_df['week']!=2]
schedule_df = schedule_df[schedule_df['week']!=3]

In [5]:
## elo data
elo = pd.read_csv('elo_2025_week4.csv')  ## elo pulled from https://www.nfeloapp.com/nfl-power-ratings/
teams_df = elo.copy()
teams_df = teams_df[['Team', 'nfelo']]
#make team names consistent
teams_df['Team'] = teams_df['Team'].replace({'LAR': 'LA', 'OAK': 'LV'})

## Function Definitions

In [6]:
def simulate_full_season(teams_df=teams_df.copy(), schedule_df=schedule_df.copy(), K=K, HFA=HFA, seed=starting_seed):
    """
    Input:
        teams_df: elo and team name
        schedule_df: week, home_team, away_team
        K: elo change per game
        HFA: home field advantage
        seed: for randomization

    Output:
        Dataframe: 1 row for each game throughout the entire season
            week. home_team, away_team, home_elo_before, away_elo_before, home_elo_after, away_elo_after, home_win_prob, away_win_prob, simulated_winner

    Methodology:
        Generates a record for each game.  Generates odds of each team winning, and simulates a winner based on those odds
        Updates ELO for both teams after the game, so they can be used in future games, allowing sull season to be simulated at a time
    """
    np.random.seed(seed)
    elo_ratings = teams_df.set_index('Team')['nfelo'].to_dict()
    all_game_results = []

    for week in sorted(schedule_df['week'].unique()):
        week_games = schedule_df[schedule_df['week'] == week]

        for df_index, df_game in week_games.iterrows():
            home_elo = elo_ratings[df_game['home_team']]
            away_elo = elo_ratings[df_game['away_team']]

            home_prob = 1/(1+10 **((away_elo-home_elo+HFA)/400))

            #simulate a winner
            winner = df_game['home_team'] if np.random.rand() < home_prob else df_game['away_team']

            if winner==df_game['home_team']:
                new_home_elo = home_elo + K * (1-home_prob)
                new_away_elo = away_elo + K * (home_prob-1)
            else:
                new_home_elo = home_elo + K * (0-home_prob)
                new_away_elo = away_elo + K * (home_prob-0)
            
            elo_ratings[df_game['home_team']] = new_home_elo
            elo_ratings[df_game['away_team']] = new_away_elo

            all_game_results.append({
                'week': week,
                'home_team': df_game['home_team'],
                'away_team': df_game['away_team'],
                'home_elo_before': home_elo,
                'away_elo_before': away_elo,
                'home_elo_after': new_home_elo,
                'away_elo_after': new_away_elo,
                'home_win_prob': home_prob,
                'away_win_prob': (1-home_prob),
                'simulated_winner': winner})
            
    return pd.DataFrame(all_game_results)

In [7]:
single_season_simulation = simulate_full_season(teams_df,schedule_df, 20, 50, 5)
single_season_simulation.head(5)

,week,home_team,away_team,home_elo_before,away_elo_before,home_elo_after,away_elo_after,home_win_prob,away_win_prob,simulated_winner
0,4,ARI,SEA,1501.06,1519.79,1513.012802,1507.837198,0.402360,0.597640,ARI
1,4,PIT,MIN,1499.80,1528.89,1492.037871,1536.652129,0.388106,0.611894,MIN
2,4,ATL,WAS,1464.25,1555.64,1478.108826,1541.781174,0.307059,0.692941,ATL
3,4,BUF,NO,1639.59,1340.71,1623.443665,1356.856335,0.807317,0.192683,NO
4,4,DET,CLE,1629.69,1387.68,1634.664969,1382.705031,0.751252,0.248748,DET

In [8]:
def global_survivor_path(simulated_season_df, win_metric='home_win_prob'):
    """
    Input:
        simulated_season_df: output of simulate_full_season
        win_metric: what metric you want to use to calculate path
            home_win_prob: maximze win probability, emphasis on home
            home_elo_difference: maximize elo difference between teams, emphasis on home
            home_elo_before: maximize elo before game.  emphasis on home
    
    Output:
        list of teams in order of week selected.  None is first entry for week 0

    Methodology:
        Scans the season looking for the highest value of metric.
        Then that winning team is added to used_teams, and that week is dropped from data
        Then keep iterating through until a team is selected for each week

    """
    survivor_path = [None] * (19)
    used_teams = set()
    remaining_games = simulated_season_df.copy()

    while remaining_games['week'].nunique()>0:
        if win_metric == 'home_win_prob':
            iteration_df = remaining_games.copy()
            iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['home_team']]
            if not iteration_df_1.empty:
                iteration_df_2 = iteration_df_1[iteration_df_1['home_win_prob'] == iteration_df_1['home_win_prob'].max()]
                win_team = iteration_df_2['home_team'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]
            else:
                iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['away_team']]
                iteration_df_2 = iteration_df[iteration_df['away_win_prob'] == iteration_df['away_win_prob'].max()]
                win_team = iteration_df_2['away_win_prob'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]

        
        if win_metric == 'home_elo_difference':
            iteration_df = remaining_games.copy()
            iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['home_team']]
            if not iteration_df_1.empty:
                iteration_df_2 = iteration_df_1[(iteration_df_1['home_elo_before']-iteration_df_1['away_elo_before']) == (iteration_df_1['home_elo_before'] - iteration_df_1['away_elo_before']).max()]
                win_team = iteration_df_2['home_team'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]
            else:
                iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['away_team']]
                iteration_df_2 = iteration_df_1[(iteration_df_1['home_elo_before']-iteration_df_1['away_elo_before']) == (iteration_df_1['home_elo_before'] - iteration_df_1['away_elo_before']).min()]
                win_team = iteration_df_2['away_win_prob'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]
        
        if win_metric == 'home_elo_before':
            iteration_df = remaining_games.copy()
            iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['home_team']]
            if not iteration_df_1.empty:
                iteration_df_2 = iteration_df_1[iteration_df_1['home_elo_before'] == iteration_df_1['home_elo_before'].max()]
                win_team = iteration_df_2['home_team'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]
            else:
                iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['away_team']]
                iteration_df_2 = iteration_df_1[iteration_df_1['away_elo_before'] == iteration_df_1['away_elo_before'].max()]
                win_team = iteration_df_2['away_win_prob'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]

    return survivor_path

In [9]:
single_season_path = global_survivor_path(single_season_simulation, 'home_win_prob')
single_season_path

[None,
 None,
 None,
 None,
 'HOU',
 'ARI',
 'PIT',
 'DEN',
 'PHI',
 'GB',
 'TB',
 'ATL',
 'DET',
 'IND',
 'BUF',
 'SF',
 'BAL',
 'NYJ',
 'JAX']

In [10]:
def simulate_full_season_multiple(teams_df=teams_df.copy(), schedule_df=schedule_df.copy(), K=K, HFA=HFA, simulations=num_simulations, seed = starting_seed, win_metric='home_win_prob'):
    """
    Input:
        teams_df: elo and team name
        schedule_df: week, home_team, away_team
        K: elo change per game
        HFA: home field advantage
        simulations: number of seasons you want to simulate
        seed: for randomization
            win_metric: what metric you want to use to calculate path
            home_win_prob: maximze win probability, emphasis on home
            home_elo_difference: maximize elo difference between teams, emphasis on home
            home_elo_before: maximize elo before game.  emphasis on home

    Output:
        List for each season simualted: contains all game results and best path
            Dictionary 'sim': get the number of the simulation
            Dictionary 'sim_games': get the game data for each simulated game.  Same output as simulate_full_season
            Dictionary 'sim_path': list of the teams selected by week.  Same output as global_survivor_path
    Methodology:
        Runs the simulate_full_season function and then finds the best path for that season global_survivor_path
        Increase the seed by 1, so each simulation is of a different season
    """
    all_season_results = []
    np.random.seed()

    for sim in range(simulations):
        sim_seed = seed+sim
        sim_games = simulate_full_season(teams_df.copy(), schedule_df.copy(), K, HFA, seed=sim_seed)
        sim_path = global_survivor_path(sim_games.copy(), win_metric=win_metric)

        all_season_results.append({
            'sim': sim+1,
            'sim_games': sim_games,
            'sim_path': sim_path})
    return all_season_results

In [11]:
many_season_simulation = simulate_full_season_multiple(teams_df, schedule_df, 20, 50, 100, 1, 'home_win_prob')

In [12]:
## example single season output
many_season_simulation[0]

{'sim': 1,
 'sim_games':      week home_team away_team  home_elo_before  away_elo_before  \
 0       4       ARI       SEA      1501.060000      1519.790000
 1       4       PIT       MIN      1499.800000      1528.890000
 2       4       ATL       WAS      1464.250000      1555.640000
 3       4       BUF        NO      1639.590000      1340.710000
 4       4       DET       CLE      1629.690000      1387.680000
 ..    ...       ...       ...              ...              ...
 219    18       NYG       DAL      1347.830768      1447.503236
 220    18       PHI       WAS      1625.109083      1567.629808
 221    18       PIT       BAL      1478.152034      1699.942657
 222    18        SF       SEA      1526.552320      1486.980402
 223    18        TB       CAR      1571.843001      1371.121394

      home_elo_after  away_elo_after  home_win_prob  away_win_prob  \
 0       1493.012802     1527.837198       0.402360       0.597640
 1       1492.037871     1536.652129       0.388106       0.611894
 2       1478.108826     1541.781174       0.307059       0.692941
 3       1643.443665     1336.856335       0.807317       0.192683
 4       1634.664969     1382.705031       0.751252       0.248748
 ..              ...             ...            ...            ...
 219     1361.890598     1433.443406       0.297009       0.702991
 220     1634.893845     1557.845045       0.510762       0.489238
 221     1474.692147     1703.402544       0.172994       0.827006
 222     1536.852375     1476.680348       0.484997       0.515003
 223     1557.757982     1385.206412       0.704251       0.295749

     simulated_winner
 0                SEA
 1                MIN
 2                ATL
 3                BUF
 4                DET
 ..               ...
 219              NYG
 220              PHI
 221              BAL
 222               SF
 223              CAR

 [224 rows x 10 columns],
 'sim_path': [None,
  None,
  None,
  None,
  'BUF',
  'NYJ',
  'WAS',
  'KC',
  'PHI',
  'LA',
  'CHI',
  'ATL',
  'DET',
  'LAC',
  'TB',
  'SF',
  'BAL',
  'TEN',
  'JAX']}

In [13]:
## example of simulated season number
many_season_simulation[0]['sim']

1

In [14]:
## example of output of each game in simulated season
many_season_simulation[0]['sim_games']

,week,home_team,away_team,home_elo_before,away_elo_before,home_elo_after,away_elo_after,home_win_prob,away_win_prob,simulated_winner
0,4,ARI,SEA,1501.060000,1519.790000,1493.012802,1527.837198,0.402360,0.597640,SEA
1,4,PIT,MIN,1499.800000,1528.890000,1492.037871,1536.652129,0.388106,0.611894,MIN
2,4,ATL,WAS,1464.250000,1555.640000,1478.108826,1541.781174,0.307059,0.692941,ATL
3,4,BUF,NO,1639.590000,1340.710000,1643.443665,1336.856335,0.807317,0.192683,BUF
4,4,DET,CLE,1629.690000,1387.680000,1634.664969,1382.705031,0.751252,0.248748,DET
...,...,...,...,...,...,...,...,...,...,...
219,18,NYG,DAL,1347.830768,1447.503236,1361.890598,1433.443406,0.297009,0.702991,NYG
220,18,PHI,WAS,1625.109083,1567.629808,1634.893845,1557.845045,0.510762,0.489238,PHI
221,18,PIT,BAL,1478.152034,1699.942657,1474.692147,1703.402544,0.172994,0.827006,BAL
222,18,SF,SEA,1526.552320,1486.980402,1536.852375,1476.680348,0.484997,0.515003,SF
223,18,TB,CAR,1571.843001,1371.121394,1557.757982,1385.206412,0.704251,0.295749,CAR

In [15]:
## example of optimal survivor path for simulated season
many_season_simulation[0]['sim_path']

[None,
 None,
 None,
 None,
 'BUF',
 'NYJ',
 'WAS',
 'KC',
 'PHI',
 'LA',
 'CHI',
 'ATL',
 'DET',
 'LAC',
 'TB',
 'SF',
 'BAL',
 'TEN',
 'JAX']

In [16]:
def pull_path_from_sim(seasons_list):
    """
    Inputs:
        seasons_list: output of simulate_full_season_multiple

    Outputs: 
        dataframe: simulation number as index, each week is a column
            so 1 row for each simulation with the team selected for that week ina  column

    Methodology:
        Extract the best paths data.
        Then create dataframe of simulations to make for easier analysis
    """
    all_paths = []
    for i in range(len(seasons_list)):
        sim_path = seasons_list[i]['sim_path']
        all_paths.append(sim_path)
    paths_df = pd.DataFrame(all_paths)
    paths_df.index = [f'sim_{i+1}' for i in range(len(all_paths))]
    paths_df.columns = [f'week_{i}' for i in range(paths_df.shape[1])]
    paths_df.drop('week_0', axis=1, inplace=True)

    return paths_df

In [17]:
many_season_simulation_paths = pull_path_from_sim(many_season_simulation)
many_season_simulation_paths

,week_1,week_2,week_3,week_4,week_5,week_6,week_7,week_8,week_9,week_10,week_11,week_12,week_13,week_14,week_15,week_16,week_17,week_18
sim_1,None,None,None,BUF,NYJ,WAS,KC,PHI,LA,CHI,ATL,DET,LAC,TB,SF,BAL,TEN,JAX
sim_2,None,None,None,BUF,ARI,PIT,LAC,PHI,LA,CHI,MIN,DET,BAL,TB,SF,HOU,KC,JAX
sim_3,None,None,None,BUF,ARI,GB,KC,PHI,LA,DEN,MIN,BAL,LAC,CLE,SF,HOU,IND,JAX
sim_4,None,None,None,BUF,ARI,GB,KC,PHI,LA,SEA,MIN,DET,LAC,TB,SF,BAL,NYJ,ATL
sim_5,None,None,None,HOU,ARI,PIT,DEN,PHI,GB,TB,ATL,DET,IND,BUF,SF,BAL,NYJ,JAX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
sim_96,None,None,None,DET,SEA,GB,KC,PHI,LA,CHI,NE,BAL,IND,MIN,SF,DEN,WAS,BUF
sim_97,None,None,None,BUF,ARI,GB,DEN,IND,LA,CAR,PIT,DET,MIA,KC,SF,BAL,LV,ATL
sim_98,None,None,None,BUF,ARI,PIT,DEN,PHI,LA,CHI,NE,BAL,IND,DET,SF,HOU,WAS,ATL
sim_99,None,None,None,BUF,IND,GB,KC,NE,WAS,DEN,PIT,SF,TB,DET,PHI,BAL,LAC,JAX
sim_100,None,None,None,HOU,ARI,LV,DEN,PHI,LA,CHI,ATL,DET,NE,TB,SF,MIA,IND,BUF

## Running Simulations And Analysis

In [18]:
## week 1 picks over simulations
simulated_data_home_elo_before = simulate_full_season_multiple(teams_df.copy(), schedule_df.copy(), K, HFA, simulations=10000, seed = starting_seed, win_metric='home_elo_before')
simulated_paths_home_elo_before = pull_path_from_sim(simulated_data_home_elo_before)
simulated_paths_home_elo_before.value_counts('week_4')

week_4
DET    1929
BUF    1621
SF     1085
LA     1021
DEN     954
HOU     792
ARI     578
KC      490
TB      401
PIT     393
DAL     158
MIA     157
ATL     150
NE       85
LV       76
MIN      22
LAC      21
NYG      16
WAS      15
SEA      12
IND       9
GB        6
CHI       5
PHI       2
JAX       1
CIN       1
Name: count, dtype: int64

In [19]:
## exmaple simulation
simulated_single_path_home_elo_before = simulated_paths_home_elo_before.iloc[[0]]
simulated_single_path_home_elo_before

,week_1,week_2,week_3,week_4,week_5,week_6,week_7,week_8,week_9,week_10,week_11,week_12,week_13,week_14,week_15,week_16,week_17,week_18
sim_1,None,None,None,DET,NYJ,WAS,SF,PIT,BUF,TB,MIN,LA,LAC,GB,KC,BAL,CIN,PHI

In [20]:
## week 1 picks over simulations
simulated_data_home_win_prob = simulate_full_season_multiple(teams_df.copy(), schedule_df.copy(), K, HFA, simulations=10000, seed = 1, win_metric='home_win_prob')
simulated_paths_home_win_prob = pull_path_from_sim(simulated_data_home_win_prob)
simulated_paths_home_win_prob.value_counts('week_4')

week_4
BUF    7943
HOU     821
DET     737
NE      128
MIA      71
LA       69
DEN      68
SF       58
ARI      22
LV       13
KC       10
PIT       9
LAC       9
DAL       9
ATL       7
GB        7
WAS       5
CHI       4
TB        4
NYG       3
PHI       2
MIN       1
Name: count, dtype: int64

In [21]:
## exmaple simulation
simulated_sinlge_path_home_win_prob = simulated_paths_home_win_prob.iloc[[0]]
simulated_sinlge_path_home_win_prob

,week_1,week_2,week_3,week_4,week_5,week_6,week_7,week_8,week_9,week_10,week_11,week_12,week_13,week_14,week_15,week_16,week_17,week_18
sim_1,None,None,None,BUF,NYJ,WAS,KC,PHI,LA,CHI,ATL,DET,LAC,TB,SF,BAL,TEN,JAX

In [22]:
## week 1 picks over simulations
simulated_data_home_elo_difference = simulate_full_season_multiple(teams_df.copy(), schedule_df.copy(), K, HFA, simulations=10000, seed = 1, win_metric='home_elo_difference')
simulated_paths_home_elo_difference = pull_path_from_sim(simulated_data_home_elo_difference)
simulated_paths_home_elo_difference.value_counts('week_4')

week_4
BUF    7943
HOU     821
DET     737
NE      128
MIA      71
LA       69
DEN      68
SF       58
ARI      22
LV       13
KC       10
PIT       9
LAC       9
DAL       9
ATL       7
GB        7
WAS       5
CHI       4
TB        4
NYG       3
PHI       2
MIN       1
Name: count, dtype: int64

In [23]:
## exmaple simulation
simulated_sinlge_path_home_elo_difference = simulated_paths_home_elo_difference.iloc[[0]]
simulated_sinlge_path_home_elo_difference

,week_1,week_2,week_3,week_4,week_5,week_6,week_7,week_8,week_9,week_10,week_11,week_12,week_13,week_14,week_15,week_16,week_17,week_18
sim_1,None,None,None,BUF,NYJ,WAS,KC,PHI,LA,CHI,ATL,DET,LAC,TB,SF,BAL,TEN,JAX

In [28]:
simulated_paths_home_elo_difference.value_counts('week_9')

week_9
LA     5785
GB     3374
WAS     206
DAL     149
NE       96
CIN      87
HOU      63
PIT      59
LV       57
DET      42
NYG      21
LAC      14
SF        9
JAX       8
TEN       7
MIA       7
BUF       4
ATL       4
CHI       3
IND       2
ARI       2
SEA       1
Name: count, dtype: int64