## Imports

In [10]:
import pandas as pd
import numpy as np
import nfl_data_py as nfl

## Data And Parameters

In [11]:
## modeling input paramters
K = 20  ##max elo change per game
HFA = 50  ##home field advantage
num_simulations = 10000
starting_seed = 1

In [12]:
## game level data
seasons = [2025]
schedule_df = nfl.import_schedules(years=seasons)
schedule_df = schedule_df[schedule_df['game_type']=='REG']
schedule_df=schedule_df[['week','away_team', 'home_team','result']]

In [13]:
## Remove already used weeks
schedule_df = schedule_df[schedule_df['week']!=1]
schedule_df = schedule_df[schedule_df['week']!=2]
schedule_df = schedule_df[schedule_df['week']!=3]
schedule_df = schedule_df[schedule_df['week']!=4]
schedule_df = schedule_df[schedule_df['week']!=5]
schedule_df = schedule_df[schedule_df['week']!=6]
schedule_df = schedule_df[schedule_df['week']!=7]
schedule_df = schedule_df[schedule_df['week']!=8]
schedule_df = schedule_df[schedule_df['week']!=9]
schedule_df = schedule_df[schedule_df['week']!=10]
schedule_df = schedule_df[schedule_df['week']!=11]
schedule_df = schedule_df[schedule_df['week']!=12]
schedule_df = schedule_df[schedule_df['week']!=13]
schedule_df = schedule_df[schedule_df['week']!=14]
schedule_df = schedule_df[schedule_df['week']!=15]

In [14]:
## elo data
elo = pd.read_csv('elo_2025_week16.csv')  ## elo pulled from https://www.nfeloapp.com/nfl-power-ratings/
teams_df = elo.copy()
teams_df = teams_df[['Team', 'nfelo']]
#make team names consistent
teams_df['Team'] = teams_df['Team'].replace({'LAR': 'LA', 'OAK': 'LV'})

## Function Definitions

In [15]:
def simulate_full_season(teams_df=teams_df.copy(), schedule_df=schedule_df.copy(), K=K, HFA=HFA, seed=starting_seed):
    """
    Input:
        teams_df: elo and team name
        schedule_df: week, home_team, away_team
        K: elo change per game
        HFA: home field advantage
        seed: for randomization

    Output:
        Dataframe: 1 row for each game throughout the entire season
            week. home_team, away_team, home_elo_before, away_elo_before, home_elo_after, away_elo_after, home_win_prob, away_win_prob, simulated_winner

    Methodology:
        Generates a record for each game.  Generates odds of each team winning, and simulates a winner based on those odds
        Updates ELO for both teams after the game, so they can be used in future games, allowing sull season to be simulated at a time
    """
    np.random.seed(seed)
    elo_ratings = teams_df.set_index('Team')['nfelo'].to_dict()
    all_game_results = []

    for week in sorted(schedule_df['week'].unique()):
        week_games = schedule_df[schedule_df['week'] == week]

        for df_index, df_game in week_games.iterrows():
            home_elo = elo_ratings[df_game['home_team']]
            away_elo = elo_ratings[df_game['away_team']]

            home_prob = 1/(1+10 **((away_elo-home_elo+HFA)/400))

            #simulate a winner
            winner = df_game['home_team'] if np.random.rand() < home_prob else df_game['away_team']

            if winner==df_game['home_team']:
                new_home_elo = home_elo + K * (1-home_prob)
                new_away_elo = away_elo + K * (home_prob-1)
            else:
                new_home_elo = home_elo + K * (0-home_prob)
                new_away_elo = away_elo + K * (home_prob-0)
            
            elo_ratings[df_game['home_team']] = new_home_elo
            elo_ratings[df_game['away_team']] = new_away_elo

            all_game_results.append({
                'week': week,
                'home_team': df_game['home_team'],
                'away_team': df_game['away_team'],
                'home_elo_before': home_elo,
                'away_elo_before': away_elo,
                'home_elo_after': new_home_elo,
                'away_elo_after': new_away_elo,
                'home_win_prob': home_prob,
                'away_win_prob': (1-home_prob),
                'simulated_winner': winner})
            
    return pd.DataFrame(all_game_results)

In [16]:
single_season_simulation = simulate_full_season(teams_df,schedule_df, 20, 50, 5)
single_season_simulation.head(5)

,week,home_team,away_team,home_elo_before,away_elo_before,home_elo_after,away_elo_after,home_win_prob,away_win_prob,simulated_winner
0,16,SEA,LA,1674.24,1701.78,1686.435450,1689.584550,0.390227,0.609773,SEA
1,16,WAS,PHI,1404.01,1618.29,1400.424650,1621.875350,0.179268,0.820732,PHI
2,16,CHI,GB,1524.30,1618.46,1538.226471,1604.533529,0.303676,0.696324,CHI
3,16,CAR,TB,1403.91,1447.07,1396.528896,1454.451104,0.369055,0.630945,TB
4,16,CLE,BUF,1344.69,1627.35,1342.121473,1629.918527,0.128426,0.871574,BUF

In [17]:
def global_survivor_path(simulated_season_df, win_metric='home_win_prob'):
    """
    Input:
        simulated_season_df: output of simulate_full_season
        win_metric: what metric you want to use to calculate path
            home_win_prob: maximze win probability, emphasis on home
            home_elo_difference: maximize elo difference between teams, emphasis on home
            home_elo_before: maximize elo before game.  emphasis on home
    
    Output:
        list of teams in order of week selected.  None is first entry for week 0

    Methodology:
        Scans the season looking for the highest value of metric.
        Then that winning team is added to used_teams, and that week is dropped from data
        Then keep iterating through until a team is selected for each week

    """
    survivor_path = [None] * (19)
    used_teams = set()
    used_teams.update(['WAS', 'BAL', 'SEA', 'BUF', 'ARI', 'GB', 'KC', 'IND', 'LAR', 'DET', 'LA', 'DEN', 'NE', 'PIT', 'PHI'])
    remaining_games = simulated_season_df.copy()

    while remaining_games['week'].nunique()>0:
        if win_metric == 'home_win_prob':
            iteration_df = remaining_games.copy()
            iteration_df = iteration_df[~iteration_df['simulated_winner'].isin(used_teams)]
            iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['home_team']]
            if not iteration_df_1.empty:
                iteration_df_2 = iteration_df_1[iteration_df_1['home_win_prob'] == iteration_df_1['home_win_prob'].max()]
                win_team = iteration_df_2['home_team'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]
            else:
                iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['away_team']]
                iteration_df_2 = iteration_df[iteration_df['away_win_prob'] == iteration_df['away_win_prob'].max()]
                win_team = iteration_df_2['away_win_prob'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]

        
        if win_metric == 'home_elo_difference':
            iteration_df = remaining_games.copy()
            iteration_df = iteration_df[~iteration_df['simulated_winner'].isin(used_teams)]
            iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['home_team']]
            if not iteration_df_1.empty:
                iteration_df_2 = iteration_df_1[(iteration_df_1['home_elo_before']-iteration_df_1['away_elo_before']) == (iteration_df_1['home_elo_before'] - iteration_df_1['away_elo_before']).max()]
                win_team = iteration_df_2['home_team'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]
            else:
                iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['away_team']]
                iteration_df_2 = iteration_df_1[(iteration_df_1['home_elo_before']-iteration_df_1['away_elo_before']) == (iteration_df_1['home_elo_before'] - iteration_df_1['away_elo_before']).min()]
                win_team = iteration_df_2['away_win_prob'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]
        
        if win_metric == 'home_elo_before':
            iteration_df = remaining_games.copy()
            iteration_df = iteration_df[~iteration_df['simulated_winner'].isin(used_teams)]
            iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['home_team']]
            if not iteration_df_1.empty:
                iteration_df_2 = iteration_df_1[iteration_df_1['home_elo_before'] == iteration_df_1['home_elo_before'].max()]
                win_team = iteration_df_2['home_team'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]
            else:
                iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['away_team']]
                iteration_df_2 = iteration_df_1[iteration_df_1['away_elo_before'] == iteration_df_1['away_elo_before'].max()]
                win_team = iteration_df_2['away_win_prob'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]

    return survivor_path

In [18]:
single_season_path = global_survivor_path(single_season_simulation, 'home_win_prob')
single_season_path

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'HOU',
 'CIN',
 'JAX']

In [19]:
def simulate_full_season_multiple(teams_df=teams_df.copy(), schedule_df=schedule_df.copy(), K=K, HFA=HFA, simulations=num_simulations, seed = starting_seed, win_metric='home_win_prob'):
    """
    Input:
        teams_df: elo and team name
        schedule_df: week, home_team, away_team
        K: elo change per game
        HFA: home field advantage
        simulations: number of seasons you want to simulate
        seed: for randomization
            win_metric: what metric you want to use to calculate path
            home_win_prob: maximze win probability, emphasis on home
            home_elo_difference: maximize elo difference between teams, emphasis on home
            home_elo_before: maximize elo before game.  emphasis on home

    Output:
        List for each season simualted: contains all game results and best path
            Dictionary 'sim': get the number of the simulation
            Dictionary 'sim_games': get the game data for each simulated game.  Same output as simulate_full_season
            Dictionary 'sim_path': list of the teams selected by week.  Same output as global_survivor_path
    Methodology:
        Runs the simulate_full_season function and then finds the best path for that season global_survivor_path
        Increase the seed by 1, so each simulation is of a different season
    """
    all_season_results = []
    np.random.seed()

    for sim in range(simulations):
        sim_seed = seed+sim
        sim_games = simulate_full_season(teams_df.copy(), schedule_df.copy(), K, HFA, seed=sim_seed)
        sim_path = global_survivor_path(sim_games.copy(), win_metric=win_metric)

        all_season_results.append({
            'sim': sim+1,
            'sim_games': sim_games,
            'sim_path': sim_path})
    return all_season_results

In [20]:
many_season_simulation = simulate_full_season_multiple(teams_df, schedule_df, 20, 50, 100, 1, 'home_win_prob')

In [21]:
## example single season output
many_season_simulation[0]

{'sim': 1,
 'sim_games':     week home_team away_team  home_elo_before  away_elo_before  \
 0     16       SEA        LA      1674.240000      1701.780000
 1     16       WAS       PHI      1404.010000      1618.290000
 2     16       CHI        GB      1524.300000      1618.460000
 3     16       CAR        TB      1403.910000      1447.070000
 4     16       CLE       BUF      1344.690000      1627.350000
 5     16       DAL       LAC      1498.160000      1516.570000
 6     16       MIA       CIN      1427.260000      1449.290000
 7     16        NO       NYJ      1356.560000      1267.520000
 8     16       NYG       MIN      1392.980000      1449.150000
 9     16       TEN        KC      1316.400000      1506.910000
 10    16       ARI       ATL      1386.670000      1443.680000
 11    16       DEN       JAX      1572.550000      1546.990000
 12    16       DET       PIT      1630.480000      1512.250000
 13    16       HOU        LV      1582.560000      1332.920000
 14    16       BAL        NE      1563.640000      1555.150000
 15    16       IND        SF      1556.520000      1571.440000
 16    17       WAS       DAL      1400.424650      1510.103941
 17    17       MIN       DET      1456.185876      1638.541045
 18    17        KC       DEN      1510.915787      1563.252282
 19    17       LAC       HOU      1504.626059      1567.372631
 20    17        GB       BAL      1604.533529      1574.829101
 21    17       CAR       SEA      1416.528896      1666.435450
 22    17       CIN       ARI      1437.246011      1379.656161
 23    17       CLE       PIT      1342.121473      1504.188955
 24    17       IND       JAX      1548.367101      1556.287718
 25    17       MIA        TB      1439.303989      1434.451104
 26    17       NYJ        NE      1258.638956      1543.960899
 27    17       TEN        NO      1312.394213      1365.441044
 28    17        LV       NYG      1348.107369      1385.944124
 29    17       BUF       PHI      1629.918527      1621.875350
 30    17        SF       CHI      1579.592899      1538.226471
 31    17       ATL        LA      1450.693839      1709.584550
 32    18       ATL        NO      1447.803125      1352.559131
 33    18       BUF       NYJ      1621.120305      1276.104538
 34    18       CHI       DET      1527.978028      1642.699330
 35    18       CIN       CLE      1447.027592      1337.565414
 36    18       DEN       LAC      1550.389127      1517.761857
 37    18       HOU       IND      1554.236833      1540.018916
 38    18       JAX       TEN      1564.635903      1325.276126
 39    18        LA       ARI      1712.475263      1369.874580
 40    18        LV        KC      1360.582994      1523.778942
 41    18       MIN        GB      1452.027591      1595.117019
 42    18        NE       MIA      1526.495316      1430.596163
 43    18       NYG       DAL      1373.468499      1515.806409
 44    18       PHI       WAS      1630.673572      1394.722182
 45    18       PIT       BAL      1508.745015      1584.245611
 46    18        SF       SEA      1589.841342      1669.456421
 47    18        TB       CAR      1443.158931      1413.507925

     home_elo_after  away_elo_after  home_win_prob  away_win_prob  \
 0      1666.435450     1709.584550       0.390227       0.609773
 1      1400.424650     1621.875350       0.179268       0.820732
 2      1538.226471     1604.533529       0.303676       0.696324
 3      1416.528896     1434.451104       0.369055       0.630945
 4      1342.121473     1629.918527       0.128426       0.871574
 5      1510.103941     1504.626059       0.402803       0.597197
 6      1439.303989     1437.246011       0.397801       0.602199
 7      1365.441044     1258.638956       0.555948       0.444052
 8      1385.944124     1456.185876       0.351794       0.648206
 9      1312.394213     1510.915787       0.200289       0.799711
 10     1379.656161     1450.693839       0.350692       0.649308
 11     1563.252282     1556.287718       0.464886       0.535114
 12     1638.541045     1504.188955       0.596948       0.403052
 13     1567.372631     1348.107369       0.759368       0.240632
 14     1574.829101     1543.960899       0.440545       0.559455
 15     1548.367101     1579.592899       0.407645       0.592355
 16     1394.722182     1515.806409       0.285123       0.714877
 17     1452.027591     1642.699330       0.207914       0.792086
 18     1523.778942     1550.389127       0.356842       0.643158
 19     1517.761857     1554.236833       0.343210       0.656790
 20     1595.117019     1584.245611       0.470826       0.529174
 21     1413.507925     1669.456421       0.151049       0.848951
 22     1447.027592     1369.874580       0.510921       0.489079
 23     1337.565414     1508.745015       0.227803       0.772197
 24     1540.018916     1564.635903       0.417409       0.582591
 25     1430.596163     1443.158931       0.435391       0.564609
 26     1276.104538     1526.495316       0.126721       0.873279
 27     1325.276126     1352.559131       0.355904       0.644096
 28     1360.582994     1373.468499       0.376219       0.623781
 29     1621.120305     1630.673572       0.439911       0.560089
 30     1589.841342     1527.978028       0.487578       0.512422
 31     1447.803125     1712.475263       0.144536       0.855464
 32     1436.508210     1363.854046       0.564746       0.435254
 33     1624.214191     1273.010652       0.845306       0.154694
 34     1522.393137     1648.284221       0.279245       0.720755
 35     1455.332650     1329.260356       0.584747       0.415253
 36     1540.888738     1527.262246       0.475019       0.524981
 37     1545.263098     1548.992651       0.448687       0.551313
 38     1569.668108     1320.243920       0.748390       0.251610
 39     1715.605683     1366.744160       0.843479       0.156521
 40     1356.049748     1528.312188       0.226662       0.773338
 41     1447.075809     1600.068801       0.247589       0.752411
 42     1535.181865     1421.909615       0.565673       0.434327
 43     1368.500581     1520.774326       0.248396       0.751604
 44     1635.780028     1389.615726       0.744677       0.255323
 45     1502.207895     1590.782732       0.326856       0.673144
 46     1583.408015     1675.889748       0.321666       0.678334
 47     1453.743953     1402.922903       0.470749       0.529251

    simulated_winner
 0                LA
 1               PHI
 2               CHI
 3               CAR
 4               BUF
 5               DAL
 6               MIA
 7                NO
 8               MIN
 9                KC
 10              ATL
 11              JAX
 12              DET
 13               LV
 14              BAL
 15               SF
 16              DAL
 17              DET
 18               KC
 19              LAC
 20              BAL
 21              SEA
 22              CIN
 23              PIT
 24              JAX
 25               TB
 26              NYJ
 27              TEN
 28               LV
 29              PHI
 30               SF
 31               LA
 32               NO
 33              BUF
 34              DET
 35              CIN
 36              LAC
 37              IND
 38              JAX
 39               LA
 40               KC
 41               GB
 42               NE
 43              DAL
 44              PHI
 45              BAL
 46              SEA
 47               TB  ,
 'sim_path': [None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'NO',
  'CIN',
  'JAX']}

In [22]:
## example of simulated season number
many_season_simulation[0]['sim']

1

In [23]:
## example of output of each game in simulated season
many_season_simulation[0]['sim_games']

,week,home_team,away_team,home_elo_before,away_elo_before,home_elo_after,away_elo_after,home_win_prob,away_win_prob,simulated_winner
0,16,SEA,LA,1674.240000,1701.780000,1666.435450,1709.584550,0.390227,0.609773,LA
1,16,WAS,PHI,1404.010000,1618.290000,1400.424650,1621.875350,0.179268,0.820732,PHI
2,16,CHI,GB,1524.300000,1618.460000,1538.226471,1604.533529,0.303676,0.696324,CHI
3,16,CAR,TB,1403.910000,1447.070000,1416.528896,1434.451104,0.369055,0.630945,CAR
4,16,CLE,BUF,1344.690000,1627.350000,1342.121473,1629.918527,0.128426,0.871574,BUF
5,16,DAL,LAC,1498.160000,1516.570000,1510.103941,1504.626059,0.402803,0.597197,DAL
6,16,MIA,CIN,1427.260000,1449.290000,1439.303989,1437.246011,0.397801,0.602199,MIA
7,16,NO,NYJ,1356.560000,1267.520000,1365.441044,1258.638956,0.555948,0.444052,NO
8,16,NYG,MIN,1392.980000,1449.150000,1385.944124,1456.185876,0.351794,0.648206,MIN
9,16,TEN,KC,1316.400000,1506.910000,1312.394213,1510.915787,0.200289,0.799711,KC
10,16,ARI,ATL,1386.670000,1443.680000,1379.656161,1450.693839,0.350692,0.649308,ATL
11,16,DEN,JAX,1572.550000,1546.990000,1563.252282,1556.287718,0.464886,0.535114,JAX
12,16,DET,PIT,1630.480000,1512.250000,1638.541045,1504.188955,0.596948,0.403052,DET
13,16,HOU,LV,1582.560000,1332.920000,1567.372631,1348.107369,0.759368,0.240632,LV
14,16,BAL,NE,1563.640000,1555.150000,1574.829101,1543.960899,0.440545,0.559455,BAL
15,16,IND,SF,1556.520000,1571.440000,1548.367101,1579.592899,0.407645,0.592355,SF
16,17,WAS,DAL,1400.424650,1510.103941,1394.722182,1515.806409,0.285123,0.714877,DAL
17,17,MIN,DET,1456.185876,1638.541045,1452.027591,1642.699330,0.207914,0.792086,DET
18,17,KC,DEN,1510.915787,1563.252282,1523.778942,1550.389127,0.356842,0.643158,KC
19,17,LAC,HOU,1504.626059,1567.372631,1517.761857,1554.236833,0.343210,0.656790,LAC
20,17,GB,BAL,1604.533529,1574.829101,1595.117019,1584.245611,0.470826,0.529174,BAL
21,17,CAR,SEA,1416.528896,1666.435450,1413.507925,1669.456421,0.151049,0.848951,SEA
22,17,CIN,ARI,1437.246011,1379.656161,1447.027592,1369.874580,0.510921,0.489079,CIN
23,17,CLE,PIT,1342.121473,1504.188955,1337.565414,1508.745015,0.227803,0.772197,PIT
24,17,IND,JAX,1548.367101,1556.287718,1540.018916,1564.635903,0.417409,0.582591,JAX
25,17,MIA,TB,1439.303989,1434.451104,1430.596163,1443.158931,0.435391,0.564609,TB
26,17,NYJ,NE,1258.638956,1543.960899,1276.104538,1526.495316,0.126721,0.873279,NYJ
27,17,TEN,NO,1312.394213,1365.441044,1325.276126,1352.559131,0.355904,0.644096,TEN
28,17,LV,NYG,1348.107369,1385.944124,1360.582994,1373.468499,0.376219,0.623781,LV
29,17,BUF,PHI,1629.918527,1621.875350,1621.120305,1630.673572,0.439911,0.560089,PHI
30,17,SF,CHI,1579.592899,1538.226471,1589.841342,1527.978028,0.487578,0.512422,SF
31,17,ATL,LA,1450.693839,1709.584550,1447.803125,1712.475263,0.144536,0.855464,LA
32,18,ATL,NO,1447.803125,1352.559131,1436.508210,1363.854046,0.564746,0.435254,NO
33,18,BUF,NYJ,1621.120305,1276.104538,1624.214191,1273.010652,0.845306,0.154694,BUF
34,18,CHI,DET,1527.978028,1642.699330,1522.393137,1648.284221,0.279245,0.720755,DET
35,18,CIN,CLE,1447.027592,1337.565414,1455.332650,1329.260356,0.584747,0.415253,CIN
36,18,DEN,LAC,1550.389127,1517.761857,1540.888738,1527.262246,0.475019,0.524981,LAC
37,18,HOU,IND,1554.236833,1540.018916,1545.263098,1548.992651,0.448687,0.551313,IND
38,18,JAX,TEN,1564.635903,1325.276126,1569.668108,1320.243920,0.748390,0.251610,JAX
39,18,LA,ARI,1712.475263,1369.874580,1715.605683,1366.744160,0.843479,0.156521,LA
40,18,LV,KC,1360.582994,1523.778942,1356.049748,1528.312188,0.226662,0.773338,KC
41,18,MIN,GB,1452.027591,1595.117019,1447.075809,1600.068801,0.247589,0.752411,GB
42,18,NE,MIA,1526.495316,1430.596163,1535.181865,1421.909615,0.565673,0.434327,NE
43,18,NYG,DAL,1373.468499,1515.806409,1368.500581,1520.774326,0.248396,0.751604,DAL
44,18,PHI,WAS,1630.673572,1394.722182,1635.780028,1389.615726,0.744677,0.255323,PHI
45,18,PIT,BAL,1508.745015,1584.245611,1502.207895,1590.782732,0.326856,0.673144,BAL
46,18,SF,SEA,1589.841342,1669.456421,1583.408015,1675.889748,0.321666,0.678334,SEA
47,18,TB,CAR,1443.158931,1413.507925,1453.743953,1402.922903,0.470749,0.529251,TB

In [24]:
## example of optimal survivor path for simulated season
many_season_simulation[0]['sim_path']

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'NO',
 'CIN',
 'JAX']

In [25]:
def pull_path_from_sim(seasons_list):
    """
    Inputs:
        seasons_list: output of simulate_full_season_multiple

    Outputs: 
        dataframe: simulation number as index, each week is a column
            so 1 row for each simulation with the team selected for that week ina  column

    Methodology:
        Extract the best paths data.
        Then create dataframe of simulations to make for easier analysis
    """
    all_paths = []
    for i in range(len(seasons_list)):
        sim_path = seasons_list[i]['sim_path']
        all_paths.append(sim_path)
    paths_df = pd.DataFrame(all_paths)
    paths_df.index = [f'sim_{i+1}' for i in range(len(all_paths))]
    paths_df.columns = [f'week_{i}' for i in range(paths_df.shape[1])]
    paths_df.drop('week_0', axis=1, inplace=True)

    return paths_df

In [26]:
many_season_simulation_paths = pull_path_from_sim(many_season_simulation)
many_season_simulation_paths

,week_1,week_2,week_3,week_4,week_5,week_6,week_7,week_8,week_9,week_10,week_11,week_12,week_13,week_14,week_15,week_16,week_17,week_18
sim_1,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NO,CIN,JAX
sim_2,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,HOU,SF,JAX
sim_3,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,HOU,CIN,JAX
sim_4,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NO,MIA,JAX
sim_5,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,HOU,CIN,JAX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
sim_96,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,HOU,SF,JAX
sim_97,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,DAL,TEN,CIN
sim_98,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,HOU,MIA,JAX
sim_99,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,HOU,CIN,JAX
sim_100,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,HOU,TEN,ATL

## Running Simulations And Analysis

In [27]:
## week 1 picks over simulations
simulated_data_home_elo_before = simulate_full_season_multiple(teams_df.copy(), schedule_df.copy(), K, HFA, simulations=10000, seed = starting_seed, win_metric='home_elo_before')
simulated_paths_home_elo_before = pull_path_from_sim(simulated_data_home_elo_before)
simulated_paths_home_elo_before.value_counts('week_16')

week_16
HOU    5120
CHI    1437
DAL    1380
MIA     695
CAR     492
NO      325
NYG     296
LAC      72
JAX      58
SF       48
TEN      42
CLE      26
CIN       9
Name: count, dtype: int64

In [28]:
## exmaple simulation
simulated_single_path_home_elo_before = simulated_paths_home_elo_before.iloc[[0]]
simulated_single_path_home_elo_before

,week_1,week_2,week_3,week_4,week_5,week_6,week_7,week_8,week_9,week_10,week_11,week_12,week_13,week_14,week_15,week_16,week_17,week_18
sim_1,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,CHI,SF,JAX

In [29]:
## week 1 picks over simulations
simulated_data_home_win_prob = simulate_full_season_multiple(teams_df.copy(), schedule_df.copy(), K, HFA, simulations=10000, seed = 1, win_metric='home_win_prob')
simulated_paths_home_win_prob = pull_path_from_sim(simulated_data_home_win_prob)
simulated_paths_home_win_prob.value_counts('week_16')

week_16
HOU    7514
NO     1332
DAL     481
MIA     234
CAR     149
NYG     107
ATL      57
CHI      53
MIN      39
TEN      21
CLE      13
Name: count, dtype: int64

In [30]:
## exmaple simulation
simulated_sinlge_path_home_win_prob = simulated_paths_home_win_prob.iloc[[0]]
simulated_sinlge_path_home_win_prob

,week_1,week_2,week_3,week_4,week_5,week_6,week_7,week_8,week_9,week_10,week_11,week_12,week_13,week_14,week_15,week_16,week_17,week_18
sim_1,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NO,CIN,JAX

In [31]:
## week 1 picks over simulations
simulated_data_home_elo_difference = simulate_full_season_multiple(teams_df.copy(), schedule_df.copy(), K, HFA, simulations=10000, seed = 1, win_metric='home_elo_difference')
simulated_paths_home_elo_difference = pull_path_from_sim(simulated_data_home_elo_difference)
simulated_paths_home_elo_difference.value_counts('week_16')

week_16
HOU    7514
NO     1332
DAL     481
MIA     234
CAR     149
NYG     107
ATL      57
CHI      53
MIN      39
TEN      21
CLE      13
Name: count, dtype: int64

In [32]:
## exmaple simulation
simulated_sinlge_path_home_elo_difference = simulated_paths_home_elo_difference.iloc[[0]]
simulated_sinlge_path_home_elo_difference

,week_1,week_2,week_3,week_4,week_5,week_6,week_7,week_8,week_9,week_10,week_11,week_12,week_13,week_14,week_15,week_16,week_17,week_18
sim_1,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NO,CIN,JAX

In [33]:
simulated_paths_home_elo_before.value_counts('week_17')

week_17
SF     3894
LAC    2240
CIN    1528
MIA     828
MIN     458
ATL     273
LV      189
CLE     148
TEN     133
CAR      99
JAX      68
CHI      65
NYJ      32
HOU      23
DAL      17
TB        5
Name: count, dtype: int64

In [34]:
simulated_paths_home_win_prob.value_counts('week_17')

week_17
CIN    3699
SF     3484
MIA    1025
TEN     694
LV      373
LAC     280
CLE     114
DAL     101
MIN      69
NYG      50
CAR      39
NYJ      30
ATL      27
HOU      15
Name: count, dtype: int64

In [35]:
simulated_paths_home_elo_difference.value_counts('week_17')

week_17
CIN    3699
SF     3484
MIA    1025
TEN     694
LV      373
LAC     280
CLE     114
DAL     101
MIN      69
NYG      50
CAR      39
NYJ      30
ATL      27
HOU      15
Name: count, dtype: int64