## Imports

In [1]:
import pandas as pd
import numpy as np
import nfl_data_py as nfl

## Data And Parameters

In [2]:
## modeling input paramters
K = 20  ##max elo change per game
HFA = 50  ##home field advantage
num_simulations = 10000
starting_seed = 1

In [3]:
## game level data
seasons = [2025]
schedule_df = nfl.import_schedules(years=seasons)
schedule_df = schedule_df[schedule_df['game_type']=='REG']
schedule_df=schedule_df[['week','away_team', 'home_team','result']]

In [4]:
## Remove already used weeks
schedule_df = schedule_df[schedule_df['week']!=1]
schedule_df = schedule_df[schedule_df['week']!=2]
schedule_df = schedule_df[schedule_df['week']!=3]
schedule_df = schedule_df[schedule_df['week']!=4]
schedule_df = schedule_df[schedule_df['week']!=5]
schedule_df = schedule_df[schedule_df['week']!=6]
schedule_df = schedule_df[schedule_df['week']!=7]
schedule_df = schedule_df[schedule_df['week']!=8]
schedule_df = schedule_df[schedule_df['week']!=9]
schedule_df = schedule_df[schedule_df['week']!=10]
schedule_df = schedule_df[schedule_df['week']!=11]
schedule_df = schedule_df[schedule_df['week']!=12]
schedule_df = schedule_df[schedule_df['week']!=13]
schedule_df = schedule_df[schedule_df['week']!=14]
schedule_df = schedule_df[schedule_df['week']!=15]
schedule_df = schedule_df[schedule_df['week']!=16]
schedule_df = schedule_df[schedule_df['week']!=17]

In [5]:
## elo data
elo = pd.read_csv('elo_2025_week18.csv')  ## elo pulled from https://www.nfeloapp.com/nfl-power-ratings/
teams_df = elo.copy()
teams_df = teams_df[['Team', 'nfelo']]
#make team names consistent
teams_df['Team'] = teams_df['Team'].replace({'LAR': 'LA', 'OAK': 'LV'})

## Function Definitions

In [6]:
def simulate_full_season(teams_df=teams_df.copy(), schedule_df=schedule_df.copy(), K=K, HFA=HFA, seed=starting_seed):
    """
    Input:
        teams_df: elo and team name
        schedule_df: week, home_team, away_team
        K: elo change per game
        HFA: home field advantage
        seed: for randomization

    Output:
        Dataframe: 1 row for each game throughout the entire season
            week. home_team, away_team, home_elo_before, away_elo_before, home_elo_after, away_elo_after, home_win_prob, away_win_prob, simulated_winner

    Methodology:
        Generates a record for each game.  Generates odds of each team winning, and simulates a winner based on those odds
        Updates ELO for both teams after the game, so they can be used in future games, allowing sull season to be simulated at a time
    """
    np.random.seed(seed)
    elo_ratings = teams_df.set_index('Team')['nfelo'].to_dict()
    all_game_results = []

    for week in sorted(schedule_df['week'].unique()):
        week_games = schedule_df[schedule_df['week'] == week]

        for df_index, df_game in week_games.iterrows():
            home_elo = elo_ratings[df_game['home_team']]
            away_elo = elo_ratings[df_game['away_team']]

            home_prob = 1/(1+10 **((away_elo-home_elo+HFA)/400))

            #simulate a winner
            winner = df_game['home_team'] if np.random.rand() < home_prob else df_game['away_team']

            if winner==df_game['home_team']:
                new_home_elo = home_elo + K * (1-home_prob)
                new_away_elo = away_elo + K * (home_prob-1)
            else:
                new_home_elo = home_elo + K * (0-home_prob)
                new_away_elo = away_elo + K * (home_prob-0)
            
            elo_ratings[df_game['home_team']] = new_home_elo
            elo_ratings[df_game['away_team']] = new_away_elo

            all_game_results.append({
                'week': week,
                'home_team': df_game['home_team'],
                'away_team': df_game['away_team'],
                'home_elo_before': home_elo,
                'away_elo_before': away_elo,
                'home_elo_after': new_home_elo,
                'away_elo_after': new_away_elo,
                'home_win_prob': home_prob,
                'away_win_prob': (1-home_prob),
                'simulated_winner': winner})
            
    return pd.DataFrame(all_game_results)

In [7]:
single_season_simulation = simulate_full_season(teams_df,schedule_df, 20, 50, 5)
single_season_simulation.head(5)

,week,home_team,away_team,home_elo_before,away_elo_before,home_elo_after,away_elo_after,home_win_prob,away_win_prob,simulated_winner
0,18,TB,CAR,1438.73,1394.90,1448.907568,1384.722432,0.491122,0.508878,TB
1,18,SF,SEA,1648.63,1675.22,1640.799410,1683.050590,0.391530,0.608470,SEA
2,18,ATL,NO,1487.59,1420.31,1497.093051,1410.806949,0.524847,0.475153,ATL
3,18,CIN,CLE,1503.69,1385.60,1491.754923,1397.535077,0.596754,0.403246,CLE
4,18,HOU,IND,1583.54,1467.88,1591.672335,1459.747665,0.593383,0.406617,HOU

In [8]:
def global_survivor_path(simulated_season_df, win_metric='home_win_prob'):
    """
    Input:
        simulated_season_df: output of simulate_full_season
        win_metric: what metric you want to use to calculate path
            home_win_prob: maximze win probability, emphasis on home
            home_elo_difference: maximize elo difference between teams, emphasis on home
            home_elo_before: maximize elo before game.  emphasis on home
    
    Output:
        list of teams in order of week selected.  None is first entry for week 0

    Methodology:
        Scans the season looking for the highest value of metric.
        Then that winning team is added to used_teams, and that week is dropped from data
        Then keep iterating through until a team is selected for each week

    """
    survivor_path = [None] * (19)
    used_teams = set()
    used_teams.update(['WAS', 'BAL', 'SEA', 'BUF', 'ARI', 'GB', 'KC', 'IND', 'LAR', 'DET', 'LA', 'DEN', 'NE', 'PIT', 'PHI', 'HOU', 'CIN'])
    remaining_games = simulated_season_df.copy()

    while remaining_games['week'].nunique()>0:
        if win_metric == 'home_win_prob':
            iteration_df = remaining_games.copy()
            iteration_df = iteration_df[~iteration_df['simulated_winner'].isin(used_teams)]
            iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['home_team']]
            if not iteration_df_1.empty:
                iteration_df_2 = iteration_df_1[iteration_df_1['home_win_prob'] == iteration_df_1['home_win_prob'].max()]
                win_team = iteration_df_2['home_team'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]
            else:
                iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['away_team']]
                iteration_df_2 = iteration_df[iteration_df['away_win_prob'] == iteration_df['away_win_prob'].max()]
                win_team = iteration_df_2['away_win_prob'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]

        
        if win_metric == 'home_elo_difference':
            iteration_df = remaining_games.copy()
            iteration_df = iteration_df[~iteration_df['simulated_winner'].isin(used_teams)]
            iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['home_team']]
            if not iteration_df_1.empty:
                iteration_df_2 = iteration_df_1[(iteration_df_1['home_elo_before']-iteration_df_1['away_elo_before']) == (iteration_df_1['home_elo_before'] - iteration_df_1['away_elo_before']).max()]
                win_team = iteration_df_2['home_team'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]
            else:
                iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['away_team']]
                iteration_df_2 = iteration_df_1[(iteration_df_1['home_elo_before']-iteration_df_1['away_elo_before']) == (iteration_df_1['home_elo_before'] - iteration_df_1['away_elo_before']).min()]
                win_team = iteration_df_2['away_win_prob'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]
        
        if win_metric == 'home_elo_before':
            iteration_df = remaining_games.copy()
            iteration_df = iteration_df[~iteration_df['simulated_winner'].isin(used_teams)]
            iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['home_team']]
            if not iteration_df_1.empty:
                iteration_df_2 = iteration_df_1[iteration_df_1['home_elo_before'] == iteration_df_1['home_elo_before'].max()]
                win_team = iteration_df_2['home_team'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]
            else:
                iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['away_team']]
                iteration_df_2 = iteration_df_1[iteration_df_1['away_elo_before'] == iteration_df_1['away_elo_before'].max()]
                win_team = iteration_df_2['away_win_prob'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]

    return survivor_path

In [9]:
single_season_path = global_survivor_path(single_season_simulation, 'home_win_prob')
single_season_path

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'JAX']

In [10]:
def simulate_full_season_multiple(teams_df=teams_df.copy(), schedule_df=schedule_df.copy(), K=K, HFA=HFA, simulations=num_simulations, seed = starting_seed, win_metric='home_win_prob'):
    """
    Input:
        teams_df: elo and team name
        schedule_df: week, home_team, away_team
        K: elo change per game
        HFA: home field advantage
        simulations: number of seasons you want to simulate
        seed: for randomization
            win_metric: what metric you want to use to calculate path
            home_win_prob: maximze win probability, emphasis on home
            home_elo_difference: maximize elo difference between teams, emphasis on home
            home_elo_before: maximize elo before game.  emphasis on home

    Output:
        List for each season simualted: contains all game results and best path
            Dictionary 'sim': get the number of the simulation
            Dictionary 'sim_games': get the game data for each simulated game.  Same output as simulate_full_season
            Dictionary 'sim_path': list of the teams selected by week.  Same output as global_survivor_path
    Methodology:
        Runs the simulate_full_season function and then finds the best path for that season global_survivor_path
        Increase the seed by 1, so each simulation is of a different season
    """
    all_season_results = []
    np.random.seed()

    for sim in range(simulations):
        sim_seed = seed+sim
        sim_games = simulate_full_season(teams_df.copy(), schedule_df.copy(), K, HFA, seed=sim_seed)
        sim_path = global_survivor_path(sim_games.copy(), win_metric=win_metric)

        all_season_results.append({
            'sim': sim+1,
            'sim_games': sim_games,
            'sim_path': sim_path})
    return all_season_results

In [11]:
many_season_simulation = simulate_full_season_multiple(teams_df, schedule_df, 20, 50, 100, 1, 'home_win_prob')

In [12]:
## example single season output
many_season_simulation[0]

{'sim': 1,
 'sim_games':     week home_team away_team  home_elo_before  away_elo_before  \
 0     18        TB       CAR          1438.73          1394.90
 1     18        SF       SEA          1648.63          1675.22
 2     18       ATL        NO          1487.59          1420.31
 3     18       CIN       CLE          1503.69          1385.60
 4     18       HOU       IND          1583.54          1467.88
 5     18       JAX       TEN          1578.26          1331.15
 6     18       MIN        GB          1434.83          1511.12
 7     18       NYG       DAL          1430.72          1491.25
 8     18       BUF       NYJ          1606.38          1222.20
 9     18       CHI       DET          1580.86          1600.22
 10    18       DEN       LAC          1568.02          1539.36
 11    18        LA       ARI          1682.99          1334.64
 12    18        LV        KC          1285.17          1423.86
 13    18        NE       MIA          1590.54          1359.00
 14    18       PHI       WAS          1624.49          1317.46
 15    18       PIT       BAL          1494.82          1531.40

     home_elo_after  away_elo_after  home_win_prob  away_win_prob  \
 0      1448.907568     1384.722432       0.491122       0.508878
 1      1640.799410     1683.050590       0.391530       0.608470
 2      1497.093051     1410.806949       0.524847       0.475153
 3      1511.754923     1377.535077       0.596754       0.403246
 4      1591.672335     1459.747665       0.593383       0.406617
 5      1583.126056     1326.283944       0.756697       0.243303
 6      1448.312860     1497.637140       0.325857       0.674143
 7      1443.798159     1478.171841       0.346092       0.653908
 8      1608.929002     1219.650998       0.872550       0.127450
 9      1572.830237     1608.249763       0.401488       0.598512
 10     1578.633443     1528.746557       0.469328       0.530672
 11     1686.034022     1331.595978       0.847799       0.152201
 12     1300.123260     1408.906740       0.252337       0.747663
 13     1575.743619     1373.796381       0.739819       0.260181
 14     1628.199806     1313.750194       0.814510       0.185490
 15     1487.261639     1538.958361       0.377918       0.622082

    simulated_winner
 0                TB
 1               SEA
 2               ATL
 3               CIN
 4               HOU
 5               JAX
 6               MIN
 7               NYG
 8               BUF
 9               DET
 10              DEN
 11               LA
 12               LV
 13              MIA
 14              PHI
 15              BAL  ,
 'sim_path': [None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'JAX']}

In [13]:
## example of simulated season number
many_season_simulation[0]['sim']

1

In [14]:
## example of output of each game in simulated season
many_season_simulation[0]['sim_games']

,week,home_team,away_team,home_elo_before,away_elo_before,home_elo_after,away_elo_after,home_win_prob,away_win_prob,simulated_winner
0,18,TB,CAR,1438.73,1394.90,1448.907568,1384.722432,0.491122,0.508878,TB
1,18,SF,SEA,1648.63,1675.22,1640.799410,1683.050590,0.391530,0.608470,SEA
2,18,ATL,NO,1487.59,1420.31,1497.093051,1410.806949,0.524847,0.475153,ATL
3,18,CIN,CLE,1503.69,1385.60,1511.754923,1377.535077,0.596754,0.403246,CIN
4,18,HOU,IND,1583.54,1467.88,1591.672335,1459.747665,0.593383,0.406617,HOU
5,18,JAX,TEN,1578.26,1331.15,1583.126056,1326.283944,0.756697,0.243303,JAX
6,18,MIN,GB,1434.83,1511.12,1448.312860,1497.637140,0.325857,0.674143,MIN
7,18,NYG,DAL,1430.72,1491.25,1443.798159,1478.171841,0.346092,0.653908,NYG
8,18,BUF,NYJ,1606.38,1222.20,1608.929002,1219.650998,0.872550,0.127450,BUF
9,18,CHI,DET,1580.86,1600.22,1572.830237,1608.249763,0.401488,0.598512,DET
10,18,DEN,LAC,1568.02,1539.36,1578.633443,1528.746557,0.469328,0.530672,DEN
11,18,LA,ARI,1682.99,1334.64,1686.034022,1331.595978,0.847799,0.152201,LA
12,18,LV,KC,1285.17,1423.86,1300.123260,1408.906740,0.252337,0.747663,LV
13,18,NE,MIA,1590.54,1359.00,1575.743619,1373.796381,0.739819,0.260181,MIA
14,18,PHI,WAS,1624.49,1317.46,1628.199806,1313.750194,0.814510,0.185490,PHI
15,18,PIT,BAL,1494.82,1531.40,1487.261639,1538.958361,0.377918,0.622082,BAL

In [15]:
## example of optimal survivor path for simulated season
many_season_simulation[0]['sim_path']

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'JAX']

In [16]:
def pull_path_from_sim(seasons_list):
    """
    Inputs:
        seasons_list: output of simulate_full_season_multiple

    Outputs: 
        dataframe: simulation number as index, each week is a column
            so 1 row for each simulation with the team selected for that week ina  column

    Methodology:
        Extract the best paths data.
        Then create dataframe of simulations to make for easier analysis
    """
    all_paths = []
    for i in range(len(seasons_list)):
        sim_path = seasons_list[i]['sim_path']
        all_paths.append(sim_path)
    paths_df = pd.DataFrame(all_paths)
    paths_df.index = [f'sim_{i+1}' for i in range(len(all_paths))]
    paths_df.columns = [f'week_{i}' for i in range(paths_df.shape[1])]
    paths_df.drop('week_0', axis=1, inplace=True)

    return paths_df

In [17]:
many_season_simulation_paths = pull_path_from_sim(many_season_simulation)
many_season_simulation_paths

,week_1,week_2,week_3,week_4,week_5,week_6,week_7,week_8,week_9,week_10,week_11,week_12,week_13,week_14,week_15,week_16,week_17,week_18
sim_1,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,JAX
sim_2,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,JAX
sim_3,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,ATL
sim_4,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,JAX
sim_5,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,JAX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
sim_96,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,JAX
sim_97,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,JAX
sim_98,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,JAX
sim_99,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,JAX
sim_100,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,JAX

## Running Simulations And Analysis

In [18]:
## week 1 picks over simulations
simulated_data_home_elo_before = simulate_full_season_multiple(teams_df.copy(), schedule_df.copy(), K, HFA, simulations=10000, seed = starting_seed, win_metric='home_elo_before')
simulated_paths_home_elo_before = pull_path_from_sim(simulated_data_home_elo_before)
simulated_paths_home_elo_before.value_counts('week_18')

week_18
SF     3887
JAX    2721
CHI    2477
ATL     475
TB      225
MIN      69
NYG      45
LAC      39
DAL      37
LV       25
Name: count, dtype: int64

In [19]:
## exmaple simulation
simulated_single_path_home_elo_before = simulated_paths_home_elo_before.iloc[[0]]
simulated_single_path_home_elo_before

,week_1,week_2,week_3,week_4,week_5,week_6,week_7,week_8,week_9,week_10,week_11,week_12,week_13,week_14,week_15,week_16,week_17,week_18
sim_1,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,JAX

In [20]:
## week 1 picks over simulations
simulated_data_home_win_prob = simulate_full_season_multiple(teams_df.copy(), schedule_df.copy(), K, HFA, simulations=10000, seed = 1, win_metric='home_win_prob')
simulated_paths_home_win_prob = pull_path_from_sim(simulated_data_home_win_prob)
simulated_paths_home_win_prob.value_counts('week_18')

week_18
JAX    7489
ATL    1303
TB      614
CHI     233
SF      146
DAL      76
NYG      68
MIN      46
LV       25
Name: count, dtype: int64

In [21]:
## exmaple simulation
simulated_sinlge_path_home_win_prob = simulated_paths_home_win_prob.iloc[[0]]
simulated_sinlge_path_home_win_prob

,week_1,week_2,week_3,week_4,week_5,week_6,week_7,week_8,week_9,week_10,week_11,week_12,week_13,week_14,week_15,week_16,week_17,week_18
sim_1,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,JAX

In [22]:
## week 1 picks over simulations
simulated_data_home_elo_difference = simulate_full_season_multiple(teams_df.copy(), schedule_df.copy(), K, HFA, simulations=10000, seed = 1, win_metric='home_elo_difference')
simulated_paths_home_elo_difference = pull_path_from_sim(simulated_data_home_elo_difference)
simulated_paths_home_elo_difference.value_counts('week_18')

week_18
JAX    7489
ATL    1303
TB      614
CHI     233
SF      146
DAL      76
NYG      68
MIN      46
LV       25
Name: count, dtype: int64

In [23]:
## exmaple simulation
simulated_sinlge_path_home_elo_difference = simulated_paths_home_elo_difference.iloc[[0]]
simulated_sinlge_path_home_elo_difference

,week_1,week_2,week_3,week_4,week_5,week_6,week_7,week_8,week_9,week_10,week_11,week_12,week_13,week_14,week_15,week_16,week_17,week_18
sim_1,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,JAX

In [24]:
simulated_paths_home_elo_before.value_counts('week_17')

Series([], Name: count, dtype: int64)

In [25]:
simulated_paths_home_win_prob.value_counts('week_17')

Series([], Name: count, dtype: int64)

In [26]:
simulated_paths_home_elo_difference.value_counts('week_17')

Series([], Name: count, dtype: int64)